var romData = ["TkVTGgIBAQAAAAAAAAAAAHjYqRCNACCi/5qtAiAQ+60CIBD7oP6iBb3XB8kKsAzKEPat/wfJpdAC" + 
			   "oNYgzJCNEUCNcAeppY3/B42nB6kPjRVAqQaNASAgIIIgGY7udAeteAcJgCDtjkxXgAGkyOwQAEFB" + 
			   "TDQ8RFRofKi/3u8DjIyMjQMDA42NjY2NjY2NjY2NAECteAcpf414Byl+jQAgrXkHKeasdAfQBa15" + 
			   "BwkejXkHKeeNASCuAiCpACDmjo0DIKkCjRRArnMHvVqAhQC9bYCFASDdjqAArnMH4AbQAci+gICp" + 
			   "AJ0AA50BA41zB615B40BICDQ8iBcjiCCgSCXj612B0qwJa1HB/AFzkcH0BmiFM5/BxAHqRSNfwei" + 
			   "I72AB/AD3oAHyhD15gmiAKAHracHKQKFAK2oBykCRQAY8AE4fqcH6IjQ+a0iB/AfrQIgKUDQ+a12" + 
			   "B0qwBiAjgiDGga0CIClA8PmgFIjQ/a0/B40FIK1AB40FIK14B0iNACCtdgdKsAMgEoKtAiBoCYCN" + 
			   "ACBArXAHyQLwC8kB0DitcgfJA9AxrXcH8ATOdwdgrfwGKRDwGa12BymA0BqpK413B612B6jIhPpJ" + 
			   "AQmA0AWtdgcpf412B2CsTgepKIUAog695AbFAJAPrOAGGHnhBpADGGUAneQGyhDnruAG6OAD0AKi" + 
			   "AI7gBqIIoAK56Qad8QYYaQid8gYYaQid8wbKysqIEOhgrXAHIASOMYLcrouDGJKgACygBKn4mQAC" + 
			   "yMjIyND3YK1yByAEjs+PZ4VhkEWCBCBzAQAAoACt/AYN/QbJEPAEyZDQA0zYgskg8BquogfQC42A" + 
			   "ByBrg7BgTMCCrvwH8ErJQNBGyK2iB/BOqRiNogetgAfQNqkQjYAHwAHwDq16B0kBjXoHICWDTLuC" + 
			   "rmsH6IopB41rByAOg70/gp0AA+jgBjD1rF8HyIwEA6kAjfwGIOqupQ7JBtBEqQCNcAeNcgeNIgfu" + 
			   "dAdgrKIH8OwKkAat/QcgDoMgA5zuXQfuZAfuVwfucAet/AeNagepAI1yB42iB6IXqQCd3QfKEPpg" + 
			   "jV8HjWYHogCOYAeOZwdgByJJg84kJACgB7kdg5kAA4gQ9616B/AKqSSNBAOpzo0GA2ABgAKBQYAB" + 
			   "QsICgEHBQcEBwQECgACbEBgFLCAkFVoQICgwIBCAIDAwAf8ArhcHrRgH0A3o7hcHOL1Ug40YB/AK" + 
			   "vT+DjfwGzhgHGGAgoIOtcgfwB6IAhgggR8AgKvFM6e6tcgcgBI7sz7CDvYP2g2GErhsH6IY0qQiF" + 
			   "/ExOh6AAhDWlbcU00AalhslgsAPmNciYIOawrRoHxTTwFq1oBxhpgI1oB6kBaQCoIMSvIG+v5jWl" + 
			   "NfBoYK1JB9BIrRkH8BjJCbA/rF8HwAfQCckDkDTpAUwYhMkCkCuo0AitUwfwFMjQEcitXwfJB/AJ" + 
			   "iMAEsCbAA7APwAPQBKkEhfyYGGkMjXMHrUkHGGkEjUkHrRkHaQCNGQfJB5AIqQaNoQfucgdgraEH" + 
			   "0CCsXwfAB7AaqQCNYAeNXAeNcgfuXwcgA5zuVwepAY1wB2Ct/AYN/QYpQPANqQGN/Aep/41aByBI" + 
			   "kmD///b79/v4+/n7+vv2UPdQ+FD5UPpQ/f7/QUJERUgxMjQ1OAC9EAHwvskLkAWpC50QAai9LAHQ" + 
			   "BJ0QAWDeLAHJK9AewAvQB+5aB6lAhf65t4RKSkpKqrm3hCkPnTQBICe8vOUGtRbJEvAiyQ3wHskF" + 
			   "8BLJCvAWyQvwEskJsAa1HskCsAiu7gO87AamCL0eAckYkAXpAZ0eAb0eAekIIMHlvRcBmQMCGGkI" + 
			   "mQcCqQKZAgKZBgK9EAEKqr2fhJkBAr2ghJkFAqYIYK08ByAEjouFm4VShlqGk4adiKiGnYjmhr+F" + 
			   "44VDhv+GModJhyAggiAZjq1wB/AyogNMxYWtRAdIrVYHSKkAjVYHqQKNRAcg8YVojVYHaI1EB0xF" + 
			   "hwECAwSsTge+u4WOcwdMRYcACQoEIiIPDw8iDw8iFicYIjAnGSI3JxasRAfwBrnHhY1zB+48B64A" + 
			   "A6AArVMH8AKgBK1WB8kC0AKgCKkDhQC514WdBAPI6MYAEPSuAAOsRAfQA6xOB7nPhZ0EA6k/nQED" + 
			   "qRCdAgOpBJ0DA6kAnQgDihhpB40AA2CtMwfJAdAFqQuNcwdMRYepACAIiExFhyAwvK4AA6kgnQED" + 
			   "qXOdAgOpA50DA6xfB8iYnQQDqSidBQOsXAfImJ0GA6kAnQcDihhpBo0AA0xFh61ZB/AKqQCNWQep" + 
			   "AkzHhu48B0xFh61wB/AzyQPwIq1SB9AqrE4HwAPwBa1pB9AeIKTvqQEgCIggpYipAI10B2CpEo2g" + 
			   "B6kDIAiITE6HqQiNPAdg7nQHILCSrR8H0PjOHgcQA+48B6kGjXMHYK1wB9BKqR6NBiCpwI0GIKkD" + 
			   "hQGgAIQArQcgrQcgkQDI0ALmAaUByQTQ8MA6kOypBUxMhq1wB9AXogCdAAOdAATK0PcgJYPuPAdg" + 
			   "qfogNrzucgdgIEMFFgobEhggUgsgGBsVDSQkHRIWDiBoBQAkJC4pI8B/qiPCAer/Ic0HJCQpJCQk" + 
			   "JCFLCSAYGxUNJCQoJCIMRyQj3AG6/yHNBRYKGxIYIgwHHRIWDiQeGf8hzQUWChsSGCILCRAKFg4k" + 
			   "GB8OG/8lhBUgDhUMGBYOJB0YJCAKGxkkIxgXDismJQEkJi0BJCY1ASQn2UaqJ+FFqv8VHhIQEgQD" + 
			   "AgAkBSQACAcGAAAAJydGTllhbm5ICqjABJAMwAiQAqAIrXoH0AHIvv6HoAC9UofJ//AHmQED6MjQ" + 
			   "8qkAmQEDaKrJBLBJytAjrVoHGGkByQqQB+kKoJ+MCAONCQOsXwfIjBQDrFwHyIwWA2CtegfwHa1T" + 
			   "B8rQCaxwB8AD8AJJAUqQC6AEue2HmQQDiBD3YOkECgqqoAC98oeZHAPoyMjIyMAMkPGpLEw/hq2g" + 
			   "B9ALICCCqQeNoAfuPAdgrSYHKQGFBaxAA4QArSEHmUIDrSAHmUEDqZqZQwOpAIUEqoYBvaEGKcCF" + 
			   "AwoqKqi5CIuFBrkMi4UHvaEGCgqFAq0fBykBSQEKZQKopgCxBp1EA8ixBp1FA6QEpQXQDqUBSrAZ" + 
			   "JgMmAyYDTDCJpQFKsA9GA0YDRgNGA0wwiUYDRgPmBLn5AwUDmfkD5gDmAKYB6OANkI2kAMjIyKkA" + 
			   "mUEDjEAD7iEHrSEHKR/QDamAjSEHrSAHSQSNIAdMvYmtIQcpHzjpBCkfhQGtIAewAkkEKQQJI4UA" + 
			   "pQFKSmnAhQGiAKxAA6UAmUEDpQEYaQiZQgOFAb35A5lEA6kBmUMDSp35A8jIyMjo4AeQ2ZlBA4xA" + 
			   "A6kGjXMHYCcnJxcHFz8MBP////8ADwcSDw8HFw8PBxccDwcXAKUJKQfQUa4AA+AxsEqoucmJnQED" + 
			   "6MjACJD0rgADqQOFAK1OBwoKqLnRiZ0EA8joxgAQ9K4AA6zUBrnDiZ0FA60AAxhpB40AA+7UBq3U" + 
			   "BskGkAWpAI3UBmBFRUdHR0dHR1dYWVokJCQkJiYmJqBBqQOuTgfQAqkEIJeKqQaNcwdgIG2K7vAD" + 
			   "3uwDYKkAoAPJAPAUoADJWPAOyVHwCsjJXfAFyVLwAciYrAADyCCXioiYGGkKTD+GhgCEAQoKqqAg" + 
			   "pQbJ0JACoCSEAykPCoUEqQCFBaUCGGkgCiYFCiYFZQSFBKUFaQAYZQOFBaQBvTmKmQMDvTqKmQQD" + 
			   "vTuKmQgDvTyKmQkDpQSZAQMYaSCZBgOlBZkAA5kFA6kCmQIDmQcDqQCZCgOmAGAQrGSMi4uMjCQk" + 
			   "JCQnJycnJCQkNTYlNyUkOCQkJDAwJiYmNCYkMSQyMyYkMzQmJiYmJiYmJMAkwCR/fyS4urm7uLy5" + 
			   "vbq8u71gZGFlYmZjZ2BkYWViZmNnaGhpaSYmampLTE1OTU9NT01OUFFrcCwtbHFtcm5zb3SGioeL" + 
			   "iIyIjImNaWmOkY+SJpMmk5CUaWmk6errJCQkJCQvJD2ioqOjJCQkJKKio6OZJJkkJKI+P1tcJKMk" + 
			   "JCQknUeeR0dHJydHR0dHJydHR6lHqkebJ5wnJycnJ1JSUlKAoIGhvr6/v3W6dru6uru7RUdFR0dH" + 
			   "R0dFR0VHtLa1t0VHRUdFR0VHRUdFR0VHRUdFR0VHR0dHR0dHR0dHR0dHR0dHR0dHR0ckJCQkJCQk" + 
			   "JKusra5dXl1ewSTBJMbIx8nKzMvNKipAQCQkJCQkRyRHgoOEhSRHJEeGioeLjpGPkiQvJD0kJCQ1" + 
			   "NiU3JSQ4JCQkJDkkOiQ7JDwkJCRBJkEmJiYmJrCxsrN3eXd5U1VUVlNVVFalp6aowsTDxVdZWFp7" + 
			   "fXx+PwAgDxUSJQ86Gg8PMBIPDycSDyIWJxgPEDAnDxYwJw8PMBAAPwAgDykaDw82Fw8PMCEPDycX" + 
			   "Dw8WJxgPGjAnDxYwJw8PNhcAPwAgDykaCQ88HA8PMCEcDycXHA8WJxgPHDYXDxYwJw8MPBwAPwAg" + 
			   "DzAQAA8wEAAPMBYADycXAA8WJxgPHDYXDxYwJw8AMBAAPwAEIjAAEAA/AAQPMAAQAD8ABCInFg8A" + 
			   "PxQEDxowJwAlSBAdEQoXFCQiGB4kFgobEhgrACVIEB0RChcUJCIYHiQVHhIQEisAJcUWCx4dJBge" + 
			   "GyQZGxIXDA4cHCQSHCQSFyYFDwoXGB0RDhskDAocHRUOKwAlpxMiGB4bJBoeDhwdJBIcJBgfDhuv" + 
			   "ACXjGyAOJBkbDhwOFx0kIhgeJAokFw4gJBoeDhwdrwAmSg0ZHhwRJAseHR0YFyQLACaIER0YJBwO" + 
			   "FQ4MHSQKJCAYGxUNAAqoaIUEaIUFyLEEhQbIsQSFB2wGAK0CIK14BwkQKfAg7Y6pJCAtjqkgjQYg" + 
			   "qQCNBiCiBKDAqSSNByCI0PrK0PegQIqNAAONAQONByCI0PqNPweNQAdM5o6pAY0WQEqqjRZAIGqO" + 
			   "6KAISL0WQIUASgUASmgqiNDxnfwGSCkwPUoH8AdoKc+d/AZgaJ1KB2CNBiDIsQCNBiDIsQAKSK14" + 
			   "BwkEsAIp+yDtjmgKkAMJAshKSqqwAcixAI0HIMrQ9TiYZQCFAKkAZQGFAak/jQYgqQCNBiCNBiCN" + 
			   "BiCuAiCgALEA0KyNBSCNBSBgjQAgjXgHYPAGYgZiBm0CbQJ6AwYMEhgeJIUAIBGPpQBKSkpKGGkB" + 
			   "KQ/JBrBESAqorgADqSDAANACqSKdAQO59I6dAgO59Y6dAwOFA4YCaKq9AI84+fWOqKYCudcHnQQD" + 
			   "6MjGA9D0qQCdBAPo6OiOAANgrXAHyQDwFqIFvTQBGHnXBzAWyQqwGZnXB4jKEOypAKIGnTMByhD6" + 
			   "YN4zAakJ0Oc46Qr+MwFMdY+iBSCej6ILoAU4vd0H+dcHyogQ9pAO6Mi93QeZ1wfoyMAGkPRgBDBI" + 
			   "YHiQqMDY6CT4/CgsGP8jWKBvIMyQoB+ZsAeIEPqpGI2iByADnKBLIMyQoiGpAJ2AB8oQ+q1bB6xS" + 
			   "B/ADrVEHjRoHjSUHjSgHIDiwoCApAfACoCSMIAeggIwhBwoKCgqNoAbOMAfOMQfOMgepC40eByAi" + 
			   "nK1qB9AQrV8HyQSQDNAHrVwHyQKQA+7MBq1bB/AFqQKNEAepgIX7qQGNdAfucgdgqQGNVweNVAep" + 
			   "Ao1aB41hB6kAjXQHqJkAA8jQ+o1ZB41pB40oB6n/jaADrRoHTngHKQFqLngHIO2QqTiN4wapSI3i" + 
			   "BqlYjeEGog69vI+d5AbKEPegA7nLj5kAAogQ9yCvkiCqku4iB+5yB2CiB6kAhQaGB+AB0ATAYLAC" + 
			   "kQaIwP/Q8coQ7GACAQQIECCtcAfwI61SB8kC8A2gBa0QB8kG8A7JB/AKrE4HrUMH8AKgBLnnkIX7" + 
			   "YCgYOCgIAAAgsFAAALCw8AAgAAAAAAAAIAQDAq0aB4VtqSiNCgepAYUzhbWpAIUdzpAEoACMWwet" + 
			   "TgfQAciMBAeuEAesUgfwB8AB8AO+GJG5FpGFhr0ckYXOvSWRjcQDIPGFrBUH8BqtVwfwFbktkY34" + 
			   "B6kBjfoHSo35B41XB42fB6xYB/AUqQOFHaIAIIS9qfCF16IFoAAgHrmsTgfQAyALt6kHhQ5gVkBl" + 
			   "cGZAZkBmQGZgZXAAAO50B6kAjSIHqYCF/M5aBxALqQCNcgepA41wB2CtXwcKqq1cBykC8AHovL2R" + 
			   "rVwHSpiwBEpKSkopD80aB/AEkAKpAI1bByCCkkxkkq1yByAEjiSSZ4U3kqkAjTwHjSIHqQKF/O50" + 
			   "B+5yB2CpAI10B638BikQ0AWtoAfQOamAhfwggpKQE61fB439B6kACo1yB42gB41wB2AgA5ypAY1U" + 
			   "B+5XB6kAjUcHjVYHhQ6NcgepAY1wB2A4rXoH8CGtYQcwHK1TB0kBjVMHoga9WgdIvWEHnVoHaJ1h" + 
			   "B8oQ7xhgqf+NyQZgrB8H0AWgCIwfB4iYIMiSzh8H0AMgaolgIASO25KuiK6I/JPbkq6Iroj8k+4m" + 
			   "B60mBykP0AaNJgfuJQfuoAatoAYpH42gBmAAMGCTAAAREhITAABRUlMAAAAAAAABAgIDAAAAAAAA" + 
			   "kZKTAAAAAFFSU0FCQwAAAAAAkZKXh4iJmQAAABESE6SlpaWml5iZAQIDAKSlpgAREhISEwAAAAAB" + 
			   "AgIDAKSlpaYAAAAREhITAAAAAAAAAJwAi6qqqqoREhOLAJycAAABAgMREhITAAAAAKqqnKoAiwAB" + 
			   "AgOAgwCBhACChQACAAADAAAEAAAABQYHBgoACAlNAAAND04OTk4ADRqGh4eHh4eHh4eHh2lpAAAA" + 
			   "AABFR0dHR0cAAAAAAAAAAAAAAAAAhodpVFJiAAAAGAEYBxgPGP8YAR8HHw8fgR8BAI8f8R/5GPEY" + 
			   "/x+tKAfwAyAIlaIMqQCdoQbKEPqsQgfwQq0lB8kDMAU46QMQ9woKCgp59pJtJgeqvfqS8CZIKQ84" + 
			   "6QGFAAplAKpoSkpKSqipA4UAvYqTmaEG6MjAC/AExgDQ8K5BB/ATvK2TogC5sZPwA52hBsjo4A3Q" + 
			   "8qxOB9AMrV8HyQfQBaliTIiUudiTrEMH8AKpiIUHogCtJwcKqLnck4UAyIQBrUMH8ArgAPAGpQAp" + 
			   "CIUAoAC5isYkAPAFpQedoQbo4A3wGK1OB8kC0AjgC9AEqVSFB8jACNDbpAHQviAIla2gBiDhm6IA" + 
			   "oACEAL2hBinACioqqL2hBtkElbACqQCkAJEGmBhpEKjo4A2Q3WAQUYjAogKGCKkAjSkHrCwHsefJ" + 
			   "/fBLvTAHEEbIsecKkAutKwfQBu4rB+4qB4ix5ykPyQ3QG8ix54gpQNAcrSsH0BfIsecpH40qB+4r" + 
			   "B0xulckO0AWtKAfQCK0qB80lB5AGIJWVTHGV7ikHIImVpgi9MAcwA94wB8oQjK0pB9CFrSgH0IBg" + 
			   "7iwH7iwHqQCNKwdgvTAHMAO8LQeiELHnyf3w4ykPyQ/wCKIIyQzwAqIAhgemCMkO0AipAIUHqS7Q" + 
			   "U8kN0BupIoUHyLHnKUDwY7HnKX/JS9AD7kUHKT9MFpbJDLAnyLHnKXDQC6kWhQex5ykPTBaWhQDJ" + 
			   "cNAKsecpCPAEqQCFAKUATBKWyLHnKXBKSkpKhQC9MAcQQq0qB80lB/ARrCwHsecpD8kO0AWtKAfQ" + 
			   "IWCtKAfwC6kAjSgHjSkHhQhgrCwHsecp8EpKSkrNJgfQ360sB50tByCJlaUAGGUHIASO5ZhAly6a" + 
			   "PprymVCaWZrlmEGbupd5mXyZf5lXmWiZa5nQmdeZBpi3mquYlJkOmw6bDpsBmxmbGZsZmxSbGZtv" + 
			   "mBma05qCmJ6ZCZoOmgGa8pYNlw2XK5crlyuXRZbFlrwtB8ix50gpQNASaEgpD40nB2gpMEpKSkqN" + 
			   "QgdgaCkHyQSQBY1EB6kAjUEHYKIErV8H8AjorE4HiNAB6IqN1gYgCIipDSAWl60jB0kBjSMHYIUA" + 
			   "qQCiBLQWxADQApUPyhD1YBQXGKYAvSCXoAWIMAfZFgDQ+KkAjc0GYK0zByAEjkyXeJdpmiC7m70w" + 
			   "B/AfEBGYnTAHrSUHDSYH8AWpFkywl6YHqRedoQapTEyql6kYTLCXIKybhAaQDL0wB0qdNgepGUyw" + 
			   "l6kbvDAH8B69NgeFBqYHqRqdoQbEBtAs6KlPnaEGqVDooA9MfZumB6AATH2bQkFDIKyboACwB8i9" + 
			   "MAfQAci5t5eNoQZgAEVFRQAASEdGAEVJSUlFR0dKR0dHR0tHR0lJSUlJR0pHSkdHS0dLR0dHR0dH" + 
			   "SkdKR0pLR0tHSyC7m4QHoAQgr5uKSLwwB6YHqQuFBrnPl52hBuilBvAHyMjIyMjGBuAL0Opoqq0l" + 
			   "B/A2vTAHyQHwKqQH0ATJA/AiyQLQIyDLm0ggSplolYetJQeVbqkBlbaVD6mQlc+pMZUWYKBSjKsG" + 
			   "YCC7m7wwB6YHqWudoQapbJ2iBmCgAyCvm6AKILOYsBCiBqkAnaEGyhD4ud2YjagGYBUUAAAVHh0c" + 
			   "FSEgH6ADIK+bILubiIiEBbwwB4QGpgXouZ+YyQDwCKIApAUgfZsYpAa5o5idoQa5p5idogZgERAV" + 
			   "FBMSFRQgOZmlAPAEyMjIyJhIrWAHDV8H8Cu8MAfwJiBKmbAhIMubGGkIlYetJQdpAJVuqQGVtpUP" + 
			   "INOblc+pDZUWIIfHaKimB7ndmJ2hBui535ikBohMfZugASCvmyC7m5gpB4UGvDAHYKIAGLUP8AXo" + 
			   "4AXQ9mAgrJupho2rBqILoAGph0x9m6kDLKkHSCCsm2iqqcCdoQZgqQYsqQcsqQlIIKybaKqpC52h" + 
			   "BuigAKljTH2bILubogKpbUx9m6kkjaEGogGgCKklIH2bqWGNqwYgy5s46QiFjK0lB+kAhXOpMIXU" + 
			   "qbCNDQGpMIUb5hRgogCgD0zpmYpIogGgD6lEIH2baKogu5uiAalATH2bw8LCwqxOB7numUxEmgYH" + 
			   "CMUMiaAMIK+bTA6aqQiNcwekAL75mbn8mUwgmiC7m6YHqcSgAEx9m2lhYWIiUVJSiKxOB61DB/AC" + 
			   "oAS5KZpMRJqsTge5JZpIIKybpgegAGhMfZusTge5KZpMX5qsTge5JZpIILubaKYHTH2bILubpgep" + 
			   "ZJ2hBuiIMA6pZZ2hBuiIMAWpZiB9m65qBCDTm513BK0lB51rBCDLm51xBOjgBpACogCOagRgBwcG" + 
			   "BQQDAgEAAwMEBQYHCAkKIKybkAWpCY00B840B6w0B76umrmlmqipYUx9myC7myBKmSDLm5WHrSUH" + 
			   "lW4g05uVz5VYqTKVFqABlLb2D6YHqWedoQapaJ2iBmCtXQfwNqkAjV0HTBmbIDabTCybqQCNvAYg" + 
			   "NpuEB6kArE4HiPACqQUYZQeouei9SCC7m0xImqUAOOkAqGCHAAAAIKybkC2tTgfQKK5qBCDLmzjp" + 
			   "EJ1xBK0lB+kAnWsEyMiYCgoKCp13BOjgBZACogCOagSuTge9PZuiCKAPjDUHvKEG8BjAF/AXwBrw" + 
			   "E8DA8AzAwLALwFTQBMlQ8AOdoQbo4A2wBqw1B4gQ0mAgu5u9MAcYEAWYnTAHOGC8LQex5ykPhQfI" + 
			   "secpD6hgrSYHCgoKCmClBwoKCgoYaSBgANAFBUhKSkpKqLnfm4UHaCkPGHndm4UGYP//EjYODg4y" + 
			   "MjIKJkAgE5yNUAcpYAoqKiqNTgdgrF8HubScGG1gB6i5vJxgrVAHIAmcqK1QBykfjU8HueCcGG1P" + 
			   "B6i55JyF6bkGnYXqrE4HuSidGG1PB6i5LJ2F57lOnYXooACx50gpB8kEkAWNRAepAI1BB2hIKThK" + 
			   "SkqNEAdoKcAYKioqjRUHyLHnSCkPjScHaEgpMEpKSkqNQgdoKcAYKioqyQPQBY1DB6kAjTMHpecY" + 
			   "aQKF56XoaQCF6GAABQoOExcbICUpwCZgKCkBJ2IkNSBjIilBLGEqMSZiLiMtYDMpASdkMDIhZR8G" + 
			   "HABwl7DfCh9Zfpup0AEfPFF7fKCpzvH6+zVgjqqz2AUzYHGbnZ2dnZ6enp6enp6fn5+fn5+fn5+f" + 
			   "n5+goKCgoKChoaGhoQADGRwGRcBrzjeKGY7zSM0yO3qP9lvO/5IFftcCNdh5rxCPAm/6rq6upKSl" + 
			   "paampqenqKioqKipqamqq6urrKysraGioqOjo3bdu0zqHRvMVl0WncYdNp3JHQTbSR2EG8ldiJUP" + 
			   "CDBMeC2mKJC1/w8DVhvJGw8HNhuqG0iVDwoqG1sMeC2Qtf8LjEtMd1/rDL3bGZ11HX1b2R093Zkd" + 
			   "Jp1aK4osyhsglXtc20wbzDvMeC2mKJC1/wuMOx2LHasM2x0PA2UdaxsFnQsbBZsLHYsMG4xwFXsM" + 
			   "2wwPCHgtpiiQtf8nqUsMaCkPBncbDwtgFUuMeC2Qtf8PA45l4bs4bag+5ecPCAsCKwJeZeG7DtsO" + 
			   "u47bDv5l7A8NTmXhDw5OAuAPEP7l4RuFewxblXgtkLX/pYbkKBioRYNpA8Ypm4MWpIgk6SgFqHso" + 
			   "JI/IA+gDRqiFJMgk/+uODwP7BReF244PB1cFewWbgCuF+wUPCxsFmwX/LsJm4hEPBwIRDwwSEf8O" + 
			   "wqirALuOa4LeAKAzhkMGPrSgywIPB35CpoMCDwo7Ass3DwzjDv+bjsoO7kJEW4aAuBuAULoQt1sA" + 
			   "F4VLBf40QLeGxgZbgIMA0DhbjooOpgC7DsWA8wD/HsIAawaLhmO3DwUDBiMGS7e7AFu3+zc7tw8L" + 
			   "Gzf/K9fjA8KG4gZ2paOPA4YrV2go6SjlgySPNqhbA/8PAnhASM74w/jDDwd7Q8bQD4rIUP+FhguA" + 
			   "GwDbN3eA6zf+KyArgHs4q7h3hv5CIEmGiwabgHuOW7ebDrsOm4D/C4BgOBC4wDvbjkC48Dh7jqC4" + 
			   "wLj7AKC4MLvuQogPCysOZw7/CqoOKCoOMYj/x4PXA0KPegMFpHgkpiXkJUuD4wMFpIkktSQJpGUk" + 
			   "ySQPCIUl/82ltagHqHYozCVlpKkk5SQZpA8HlSjmJBmk1ykWqVgplyn/DwICEQ8HAhH//yuCqzje" + 
			   "QuIbuOs724CLuBuC+7h7gPs8W7x7uBuOyw4bjg8NKzu7uOuCS7i7ODu3uwIPExsAy4BrvP97gK4A" + 
			   "gIuO6AX5hheGFoVOK4CrjoeFwwWLgpsCqwK7hssG0wM7jmsOp47/KY5SEYMODwObDiuOWw7LjvsO" + 
			   "+4KbgrsC/kLou44PCqsOyw75DoiGpgbbAraO/6vO3kLAy85bjhvOS4VnRQ8HKwB7hZcFDwqSAv8K" + 
			   "qg4kSh4jqv8bgLs4S7zrOw8EKwCrOOsAy477gKu4a4D7PJu7W7z7AGu4+zj/C4YaBtsG3sIC8Du7" + 
			   "gOsGC4aTBvA5DwZguBuGoLm3J70nK4OhJqkm7iULJ7T/DwIeL2DgOqWn24A7gosC/kJocLslpywn" + 
			   "sia5JpuAqIK1J7wnsLs7goc07iVr/x6lCi4oJy4zxw8DHkAHLjDnDwUeJEQPBx4iai4jqw8JHkFo" + 
			   "HiqKLiOiLjLq/zuHZifMJ+4xh+4jpzuH2wf/DwEuJSsuJUtOJctrB5dH6YdHx3oH1sd4BziHq0fj" + 
			   "B5uHDwloR9vHO8f/R5vLB/odhps6h1YHiBsHnS5l8P+bBwUyBjMHNM4D3FHuB3PgdAp+Bp4Kzgbk" + 
			   "AOgK/gouiU4LVAoUisQKNIp+BscKAeACCkcKgWCCCscKDod+AqcCswLXAuMCB4ITAj4GfgKuB/4K" + 
			   "DcTNQ84J3gvdQv4CXcf9WwcFMgYzBzReCmhkmGSoZM4G/gINAR4OfgKUY7Rj1GP0YxTjLg5eAmQ1" + 
			   "iHK+Dg0ErgLOCM1L/gINBWgxfgqWMaljqDPVMO4C5mL0YQSxCD9EM5RjpDHkMQS/CD8Evwg/zUsD" + 
			   "5A4DLgF+Br4C3gb+Cg3EzUPOCd4L3UL+Al3H/ZsHBTIGMwc0/gAnsWUydQpxALcxCOQYZB4EVzu7" + 
			   "CheKJzpzCnsK1wrnOjuKlwr+CCSKLgA+QDhkbwCfAL5DyArJY84H/gcugWZCakJ5Cr4AyGT4ZAjk" + 
			   "Lgd+A54HvgPeB/4KA6UNRM1DzgndQt4L/gJdx/2bBwUyBjMHNP4GDIE5ClwBiQqsAdkK/AEug6cB" + 
			   "twDHAd4K/gJOg1oyYwppCn4C7gP6MgOKCQoeAu4D+jIDigkKFEIeAn4Kngf+Ci6GXgqOBr4K7gc+" + 
			   "g14H/goNxEFSUVLNQ84J3gvdQv4CXcf9WwcFMgYzBzT+Cq6Gvgf+Ag0CJzJGYVViXg4egmg8dDp9" + 
			   "S16OfUt+goRilGGkMb1Lzgb+Ag0GNDE+CmQydQp7YaQzrgLeDj6CZDJ4MrQ2yDbdS0SyWDKUY6Q+" + 
			   "ujDJYc4G3UvOht1L/gIuhl4Cfgb+Ah6GPgJeBn4Cngb+Cg3EzUPOCd4L3UL+Al3H/VsGBTIGMwc0" + 
			   "XgquAg0BOXMNAzl7TUveBh6KrgbEMxb+pXf+Av6CDQc5c6h07UtJ++h0/gougmcChHqHMQ0L/gIN" + 
			   "DDlzXgbGdkX/vgrdSP4GPctGfq1K/oI586l7ToqeB/4KDcTNQ84J3gvdQv4CXcf9lBEPJv4QKJRl" + 
			   "FesS+kFKllRApEK3E+kZ9RURgEdCcROAQRWSGx8kQFUSZECVEqRA0hLhQBPALBcvEkkTg0CfFKNA" + 
			   "F5KDE5JBuRTFEshA1EBLkngbnJSfEd8U/hF9wZ5CzyD9kLEPJimRfkL+QCiSTkIuwFdzwyXHJyOE" + 
			   "MyBcAXdjiGKZYapgvAHuQk7AaRF+Qt5A+GIOwq5A12PnYzOnNydDBMwB53MMgT5CDQpeQIhyvkLn" + 
			   "h/5AOeFOAGlgh2ClYMMx/jFtwb5C7yD9UiEPIG5AWPKTAZcADIGXQKZBx0ANBAMBBwEjAScB7AOs" + 
			   "88MDeOKUQ0fzdENH+3RDLPFMY0cAVyFcAXxyOfHsAkyB2GLsAQ0NDzjHB+1KHcFfJv1UIQ8mpyI3" + 
			   "+3MggweHApMgx3ME8QYxOXFZcedzN6BHBIZ85XHnMTOkOXGpcdMjCPITBScCSXF1dehyZ/OZcecg" + 
			   "9HL3MRegMyA5cXMovAU58XlxpiHDBtMg3AD8AAeiEyFfMowAmHrHY9lhA6IHInRydzHncznxWHJ3" + 
			   "c9hyf7GXc7ZkxWXUZuNn82eNwc8m/VIxDyBuZgeBNgFmAKciCPJne9wCmPLXIDnxnzPcJ9xXI4NX" + 
			   "Y2xRh2OZYaMGsyF38/Mh9yoTgSMiUwBjIukLDIMTIRYiMwWPNewBY6BnIHMBdwGDIIcgsyC3IMMB" + 
			   "xwDTINcgZ6B3B4ci6GL1ZRyCfziNwc8m/VAhB4FHJFcAYwF3AclxaPLnc5f7BoNcAdci5wADp2wC" + 
			   "syLjAecHR6BXBqcB0wDXAQeBZyCTIgOjHGEXIW8zx2PYYulh+mBPs4djnAG3Y8hi2WHqYDnxhyGn" + 
			   "AbcgOfFfOG3Bryb9kBEPJv4QKpOHF6MUskIKkhlANhRQQYIWK5MkQbsUuADCQ8MTG5RnEsQVU8HS" + 
			   "QRLBKROFFxuSGkJHE4NBpxMOkadjt2PFZdVl3UrjZ/NnjcGuQt8g/ZARDyZuEIsXrzLYYuhi/D+t" + 
			   "yPhkDL5DQ/hkDL9zQIRAk0CkQLNA+GRI5Fw5g0CSQbNA+GRI5Fw5+GQTwjdlTCRjAJdlw0ILl6wy" + 
			   "+GQMvlNFnUj4ZCriPEdWQ7pi+GQMt4hkvDHURfwxPLF4ZIw4C5waMxhhKGE5YF1K7hEPuB3BPkJv" + 
			   "IP1SMQ8gbkD3IAeEFyBPNMMDxwLTIifjOWHnc1zkVwBsc0egUwZjIqdz/HMToTMFQyFccsMjzAN3" + 
			   "+6wCOfGnc9ME6HLjIib0vAKMgahiF4dDJKcBwwQI8pchowLJC+Fp8WmNwc8m/TgRDyatQD3H/ZWx" + 
			   "DyYNAshyHIE4cg0FlzSYYqMgswbDIMwD+ZEsgUhiDQk3Y0cDVyGMAsV5xzH5ETnxqRFvtNNl42V9" + 
			   "wb8m/QDBTAD0Tw0CAkJDT1LC3gBawk3H/ZBRDybuEAuUMxRCQncWhkQCkkoWaUJzFLAAxxIFwBwX" + 
			   "HxE2Eo8UkUAblDUSNEJgQmEShxKWQKMUHJgfEUcSnxXMFc8RBcAfFTkSfBZ/EYJAmBLfFRbEFxRU" + 
			   "EpsWKJTOAT3BXkKPIP2XEQ8m/hArklcSixLAQfcTW5JpC7sSskYZk3EAF5R8FH8Rk0G/FfwT/xEv" + 
			   "lVBCURJYFKYS2xIbk0ZDexKNSbcUG5RJC7sS/BP/EgPBLxVDEksTdxOdShXBoUHDEv4BfcGeQs8g" + 
			   "/VIhDyBuRAzxTAGqNdk07iAIszcyQwROIVMgfAGXIbcHnIHnQl+zl2OsAsVBSeBYYXZkhWWUZqQi" + 
			   "pgPIItwCaPKWQhOCFwKvNPYh/AYmgCokNgGMAP81TqBVIXcghweJIq4hTIKfNOwBA+cTZ41KrUEP" + 
			   "pv0QUUwAxxLGQgOSAkIpEmMSYkJpFKUSpELiFOFE+BY3wY84Arsoemh6qHrgavBqbcX9kjEPIG5A" + 
			   "DQI3c+wADIA8AGwAnAAGwMdzBoMocpZA53MmwId70kE58cjyl+OjI+cC4wfzIjfjnAC8AOwADIA8" + 
			   "AIYhpga2JFyAfACcACnh3AX2QdyA6HIMgSdzTAFmdA0RPzW2QSyCNkB8AoZA+WE54awExkEMgxZB" + 
			   "iPI58XwAiWGcAKdjvADFZdwA42fzZ43Bzyb9VbEPJs8zB7IVEVJCmQusAtMk1kLXJSOEzzMH4xlh" + 
			   "eHrvMyyBRmRVZWVl7HRHglMFYyFiQZYimkHMA7mROfFjJmcn0wb8ARji2QfpBAyGNyKTJIeErALC" + 
			   "QcMj2XH8AX+xnACnY7ZkzADUZuNn82eNwc8m/VCxDyb8AB+zXABlZXRmg2eTZ9xzTICzIMkLwwjT" + 
			   "L9wALIBMAIwA0y7tSvwA16HsAUyAWRHYEdoQN6BHBJkR5yE6kGcgdhB3YIcH2BI58awA6XEMgCwA" + 
			   "TAXHeznx7AD5EQyCbzT4EfoQf7KsALZkzAHjZ/NnjcHPJv1SsQ8gbkU5kbMEwyHIEcoQSZF8c+gS" + 
			   "iJGKEOchBZEHMBcHJyBJEZwByHIjpicm0wPYeomR2HI58akRCfFjJGck2GIokSoQViFwBHkLjACU" + 
			   "IZ81L7g9wX8m/QbBTAD0Tw0CBiAkTzWgNiBTRtUg1iA0oXNJdCCUILQg1CD0IC6AWUJNx/2WMQ8m" + 
			   "DQMaYHdCxADIYrnh0wbXB/lhDIFOsY6xvAHkUOlhDIENCoRDmHINDA84HcFfJv1IDw4BXgKnALxz" + 
			   "GuA5YVhid2OXY7hi1gf4YhnhdVKGQIdQlVKTQ6UhxVLWQNcg5QbmUT6NXgNnUndSfgKeA6ZDpyPe" + 
			   "Bf4CHoMzVEZARyFWBF4Cg1STUpYHl1C+A8cj/gIMgkNFRSRGJJAIlVF4+tdzOfGMAahSuFLMAV+z" + 
			   "l2OeAA6BFiRmBI4A/gEI0g4Gb0eeDw6CLUcoemh6qHquAd4PbcX9SA8OAV4CvAH8ASyCQVJOBGcl" + 
			   "aCRpJLpCxwTeC7KH/gIs4SxxZwF3AIcBjgDuAfYCA4UFAhMhFgInAi4CiHLHINcH5HYHoBcGSHp2" + 
			   "IJhyeeGIYpwBt3PcAfhi/gEI4g4AbgJzIHcjgwSTIK4A/goOgjlxqHLncwyBjzKuAP4EBNEXBCZJ" + 
			   "JynfM/4CRPZ8AY4Gv0fuD03HDoJoeq4B3g9txf1IAQ4BAFo+BkVGR0ZTRK4B30pNxw6BAFouBDco" + 
			   "OkhGR8cHzg/fSk3HDoEAWjNTQ1FGQEdQUwRVQFZQYkNkQGVQcUFzUYNRlECVUKNQpUCmULNRtkC3" + 
			   "UMNT30pNxw6BAFouAjZHN1I6SUclp1LXBN9KTccOgQBaPgJEUVNEVERVJKFUrgG0Id9K5QdNx/1B" + 
			   "AbQ0yFLyUUfTbANlSZ4HvgHMA/4HDckeAWwBYjVjU4pBrAGzU+lRJsMnM2NDZDO6YMlhzgvlCe4P" + 
			   "fcp9R/1BAbhS6kEnsrNCFtRKQqVRpzEn0wjiFmQsBDhCdmSIYt4H/gENySMyMVGYUg3JWUJjU2cx" + 
			   "FMI2MYdTF+MpYTBiPAhCN1lAakKZQMlh12M50VhSw2fTMdwG90L6QiOxQ2fDNMc00VFDs0czmjCp" + 
			   "YbhivgvVCd4PDcp9R/1JDx4BOXNeB64LHoJuiJ4CDQQuC0UJTg/tR/3/rXIHIASO5I9nhXGQ6q6u" + 
			   "Uwe9/AaN/AYgSrCtcgfJA7ABYCAktqIAhgggR8Agw4To4AbQ8yCA8SAq8SDp7iDUvqIBhgggcL7K" + 
			   "hgggcL4glrsgvLkguLcgVbggT7cg4YmltckCEBGtnwfwHskE0AitfwfQAyDtkKyfB6UJwAiwAkpK" + 
			   "SiCIskxnryCasqUKhQ2pAIUMrXMHyQbwHK0fB9AUrT0HySAwEK09B+kgjT0HqQCNQAMgsJJgrf8G" + 
			   "GG2hA43/Bq0jB9BZrVUHyVCQUq2FB9BNrP8GiDBHyMACkAGIrVUHyXCQA6z/BpiNdQcYbT0HjT0H" + 
			   "mBhtHAeNHAeNPwetGgdpAI0aBykBhQCteAcp/gUAjXgHIDiwqQiNlQdMALCpAI11B6IAIPbxhQCg" + 
			   "AAqwB8ilACkg8Bu5HAc4+TSwhYa5GgfpAIVtpQzZNrDwBKkAhVepAI2hA2AAEAECrRwHGGn/jR0H" + 
			   "rRoHaQCNGwdgpQ4gBI4xkcexBrLlsaSyyrLNkWmw6bAzskWyabJ9sq1SB8kC8CupAKTOwDCQbq0Q" + 
			   "B8kG8ATJB9BQrcQD0AWpAUzmsCAfss7eBtBQ7mkHTBWzrVgH0Ayp/yAAsqXOyZGQKGCtmQPJYNAy" + 
			   "pc7JmaAAqQGQCqkDhR3IqQiNtAWMFgcg5rClhslIkBKpCIUOqQGFM0qNUgeNFgeNWAdgjfwGpQ7J" + 
			   "C/A8rU4H0BCktYjQBqXOydCQBakAjfwGrfwGKcCFCq38BikDhQyt/AYpDIULKQTwDqUd0AqkDPAG" + 
			   "qQCFDIULICmzoAGtVAfQCaAArRQH8AKgAoyZBKkBpFfwBRABCoVFIJOvIIDxICrxogAgnOIgZNyl" + 
			   "zslAkBalDskF8BDJB/AMyQSQCK3EAynfjcQDpbXJAjA7ogGOIwegBIQHogCsWQfQBaxDB9AW6KQO" + 
			   "wAvwD6wSB9AGyIT8jBIHoAaEB8UHMAzKMAqssQfQBKkGhQ5gqQCNWAcg3bHuUgdgpbXQBqXOyeSQ" + 
			   "DKkIjVgHoAOEHUzmsKkCjVIHTBOyqQEgALIgk6+gAK3WBtAXyK1OB8kD0A/ITAuyGGXOhc5gIB+y" + 
			   "oALO3gbQDoxSB+50B6kAjXIHjSIHYKkIhVegAaWGKQ/QA4VXqJgg5rBgrUcHyfjQA0xVssnE0AMg" + 
			   "c7JgrUcHyfCwB8nI8CNM6bDQE6wLB9AOjA0H7gsHrVQHSQGNVAdgrUcHyfCwM0zpsKkAjUcHqQiF" + 
			   "DmCtRwfJwPATpQlKSikDhQCtxAMp/AUAjcQDYCBzsq3EAyn8jcQDYGClG8kw0BWtEweF/6kAjRMH" + 
			   "pM7AnrACqQRM5rDmDmAVIxYbFxgjY6kBIOawpc7JrpAOrSMH8AmpIIX8qQCNIwetkARKsA2tRgfQ" + 
			   "A+5GB6kgjcQDrUYHyQXQK+5cB61cB8kD0A6sXwetSAfZwrKQA+5dB+5gByADnO5XByATso1bB6mA" + 
			   "hfxgqQCsVAfQCKUd0AelCykEjRQHIFC0rQsH0BalHckD8AWgGIyJByAEjlqzdrNts8+zYCCPtaUM" + 
			   "8AKFMyDMtSAJv43/BmCtCgeNCQdMrLOknxATpQopgCUN0BGtCAc45c7NBgeQBq0KB40JB60EB/AU" + 
			   "II+1pc7JFLAFqRiNCQelDPAChTOlDPADIMy1IAm/jf8GpQ7JC9AFqSiNCQdMTb8OBPzyAAD//60W" + 
			   "BBhtMwSNFgSgAKWfEAGIhABlzoXOpbVlAIW1pQwtkATwLayJB9AnoBiMiQeiAKQzSrAC6OiI8AHo" + 
			   "pYYYfcezhYalbX3Ls4VtpQxJA4UzYI2JB2AgIB4oKA0EcHBgkJAKCfz8/Pv7/v8AAAAAAIAA2Ojw" + 
			   "KBgQDOSY0AD/AQAg/6UdyQPQI6AApQstkATwBsgpCNAByL5NtI4zBKkIvkq0hp8wAUqNDAdgrQ4H" + 
			   "0AqlCimA8AQlDfADTBy1pR3wEa0EB/D0rYIH0AelnxADTBy1qSCNggegAIwWBIwzBKW1jQcHpc6N" + 
			   "CAepAYUdrQAHyQmQEMjJEJALyMkZkAbIyRyQAcipAY0GB60EB/AIoAWtfQTwAci5JLSNCQe5K7SN" + 
			   "Cge5ObSNMwS5MrSFn60EB/ARqQSF/6XOyRSwEqkAhZ9MHLWpAaxUB/ACqYCF/6AAhAClHfAJrQAH" + 
			   "yRmwM5AYyK1OB/ASiKUMxUXQC6UKKUDQGa2DB9AZyOYArQMH0AetAAfJIZAK5gBMXrWpCo2DB7lA" + 
			   "tI1QBKUOyQfQAqADuUO0jVYEpAC5R7SNAgepAI0BB6UzxUXwBg4CBy4BB2ACBAegAK0AB8kcsBXI" + 
			   "yQ6wAcit/AYpf/AgKQPFRdAIqQCNAwdMxbWtAAfJC7ALpTOFRakAhVeNBQe5jLWNDAdgLZAEyQDQ" + 
			   "CKVX8EkQIzADSpAerQUHGG0CB40FB6VXbQEHhVfNVgQwI61WBIVXTCC2rQUHOO0CB40FB6VX7QEH" + 
			   "hVfNUAQQBa1QBIVXyQAQBUn/GGkBjQAHYK1WB8kCkEOlCilA8DMlDdAvrc4GKQGqtSTQJaS1iNAg" + 
			   "rRQH0BulHckD8BWpIIX/qQKVJKwMB4wRB4iMgQfuzgaiACCJtqIBIIm2rU4H0BOiAoYIIPm2IDHx" + 
			   "IJHxIOHtyhDvYEDAhgi1JAqwY7Qk8F6I8CelhmkElY2lbWkAlXSlzpXVqQGVvKQziLmHtpVeqQSV" + 
			   "pqkHnaAE1iSKGGkHqqlQhQCpA4UCqQAg178gD7+mCCA78SCH8SAt4iDI4a3SAynM0AYg2dZM3uyp" + 
			   "AJUkYCA78UwJ7b2oBykBhQe15Mn40CytkgfQP6AApTNKkAKgCJhlhpWcpW1pAJWDpc4YaQiV5KkB" + 
			   "lcukB7lNt42SB6QHvSwEOPlLt50sBLXk6QDJILACqfiV5GD/UEAgrXAH8E+lDskIkEnJC/BFpbXJ" + 
			   "ArA/rYcH0Dqt+AcN+QcN+gfwJqz4B4jQDK35Bw36B9AEqUCF/KkYjYcHoCOp/405ASBfj6mkTAaP" + 
			   "jVYHIDHZ7lkHYK0jB/D6pc4ltdD0jSMH7tYGTJjJrU4H0DeNfQStRwfQL6AEuXEEGHl3BIUCuWsE" + 
			   "8BxpAIUBpYY4+XEEpW35awQwC6UCOOWGpQHlbRAEiBDTYLl3BEqFALlxBBhlAIUBuWsEaQCFAKUJ" + 
			   "SpAspQE45YalAOVtEA6lhjjpAYWGpW3pAEw5uK2QBEqQDaWGGGkBhYalbWkAhW2pEIUAqQGNfQSF" + 
			   "AkqqTNe/BQIIBAEDAwQEBKIFhgi1Fskw0FalDskE0DGlHckD0Cu1z8mqsCilzsmisCK9FwRp/50X" + 
			   "BLXPaQGVz60OATjp/40OAa0NAekBjQ0BTKy4rA8BuUu4vlC4nTQBICe8qQWFDiCv8SBS8SBL5WAI" + 
			   "EAgAIK/xrUcH0ECtDgfwO6iImCkC0AfmzubOTNm4xs7GzrVYGHm2uJXPwAGQD6UKKYDwCSUN0AWp" + 
			   "9I3bBsAD0Aqt2waFn6kAjQ4HIFLxIH3oIHrWrQ4H8A2thgfQCKkEjYYH7g4HYKkvlRapAZUPuXYA" + 
			   "lW65jwCVh7nXAJXPrJgD0AONnQOKmZoD7pgDqQSF/mAwYOAF0GismAOIrZkD2Um58A+lCUpKkAml" + 
			   "1OkBhdTumQOtmQPJCJBGIFLxIK/xoAAgNeTIzJgD0Pet0QMpDPAQiL6aAyCYyYgQ942YA42ZA62Z" + 
			   "A8kgkBeiBqkBoBsg8OOkAsDQsAixBtAEqSaRBqYIYA8HrU4H8G+iAoYItQ/QUb2oB6zMBjm6uckG" + 
			   "sESouWsE8D65fQTwCOkAmX0ETBq6rUcH0CypDpl9BLlrBJVuuXEElYe5dwQ46QiVz6kBlbaVD0qV" + 
			   "HqkJnZoEqTOVFkwturUWyTPQDSB61rUP8AYgr/EgM7rKEJNgGOitRwfQPrUe0C6t0QMpDMkM8ECg" + 
			   "ASBD4TAByJRGiLkxupVYpQBpKMlQkCipAZUeqQqdigepCIX+tR4pIPADIGO/IAK/IK/xIFLxIEPi" + 
			   "IFPYTH3oIJjJYAQEBAUFBQYGBhDwragHKQfQBa2oBykIqLkqANAZvom6tQ/QEqYIipmuBqmQmSoA" + 
			   "qQeZogQ4YKYIGGCtRwfQY7UqKX+8rgbJAvAgsDSKGGkNqqkQhQCpD4UBqQSFAqkAINe/IA+/pghM" + 
			   "KLup/pWsuR4AKfeZHgC2Rsq9krqmCJVk1iq5hwAYaQKVk7luAGkAlXq5zwA46QqV26kBlcLQAyDE" + 
			   "1yCb8SBI8SA24iDc5GAghLu1dpl6ALWPCQWZkwC11+kQmdsATGy7IIS7veoDmXoApQYKCgoKCQWZ" + 
			   "kwClAmkgmdsAqfuZrACpAZnCAJkqAIX+hggg/rvuSAdgoAi5KgDwB4jABdD2oAiMtwZgogiGCLUq" + 
			   "8FYKkAYgw7pM9Lu0KojwHfYqtZMYbXUHlZO1emkAlXq1Kskw0CapAJUqTPS7ihhpDaqpUIUAqQaF" + 
			   "AkqFAakAINe/pgi1rMkF0AL2KiBI8SCb8SA24iCG5soQoWAXHQsRAhOpAY05Aa5TB7z4uyBfj+5e" + 
			   "B61eB8lk0AypAI1eB+5aB6lAhf6pAo04Aa5TB7z6uyBfj6xTB7n8uyAGj6wAA7n7AtAFqSSZ+wKm" + 
			   "CGCpLoUbtXaFc7WPhYypAYW7tdc46QiF1KkBhSOFFKkDjZ8EpTnJArAKrVYHyQKQAUqFOakgjcoD" + 
			   "qQKF/mCiBYYIpSPwXQqQI61HB9BDpTnwEckD8A3JAtA3IPnKIGPhTNi8IHfKIMHfTNi8pQkpA9AZ" + 
			   "xtSlI+YjyRGQD6kQlVipgIUjCo3KAyqVRqUjyQaQEiBS8SCv8SBD4iDS5iBT2CB61mAEEkipEa7u" + 
			   "A6xUB9ACqRKVJiBriq7uA6UCneQDqKUGneYDsQYg9r2FAKxUB9ABmJAloBGUJqnEpADAWPAEwF3Q" + 
			   "Fa28BtAIqQuNnQfuvAatnQfQAqDEmJ3oAyCEvaQCqSORBqkQjYQHaIUFoACtFAfQBa1UB/AByKXO" + 
			   "GHnrvCnwlde0JsAR8AYgAr5Me70gm72t7gNJAY3uA2ClhhhpCCnwlY+lbWkAlXad6gOltZW+YCAf" + 
			   "vqkChf+pAJVgnTwEhZ+p/pWopQUg9r2QMZjJCZAC6QUgBI7SvTi7OLvYvdK9373VvTi72L2pACyp" + 
			   "AiypA4U5TEm8ogWs7gMgHrlgwcBfYFVWV1hZWltcXV6gDdnovfAEiBD4GGAgH76pAZ3sA4X9IEG+" + 
			   "qf6Fn6kFjTkBICe8ru4DYK7uA6QC8BqYOOkQhQKosQbJwtANqQCRBiBNiq7uAyBRu2C1j53xA6nw" + 
			   "lWCVYqn6laip/JWqqQCdPASdPgS1dpV4tY+VkbXXGGkIldmp+pWoYLUm8F0pD0ioihhpCaqI8DMg" + 
			   "pL8gD7+KGGkCqiCkvyAPv6YIIFnxILbxIFPsaLS+8DBIqfDV2bACldm118nwaJAgsBwgpL+mCCBZ" + 
			   "8SC28SDR67XXKQ/JBWiwB6kBnewDqQCVJmCiAYYIrQED0CG97APwHL3mA4UGqQWFB73kA4UCqL3o" + 
			   "A5EGIGGKqQCd7APKENVg6CAPv6YIYK0OB9A+qrVXCgoKCoUBtVdKSkpKyQiQAgnwhQCgAMkAEAGI" + 
			   "hAK9AAQYZQGdAASpACpIarWGZQCVhrVtZQKVbWgYZQBgogCtRwfQBa0OB9DzrQkHhQCpBEytv6A9" + 
			   "tR7JBdACoCBMlL+gAEx3v6AB6KkDhQCpBoUBqQKFAphM0b+gf9ACoA+pAtAEoBypA4QA6CCtv6YI" + 
			   "YAYIoAAsoAGpUIUAuZ+/hQKpAEzXv6kALKkBSLQW6KkFwCnQAqkJhQCpCoUBqQOFAmioINe/pghg" + 
			   "SL0WBBh9MwSdFgSgALWfEAGIhAd1zpXOtbVlB5W1vTMEGGUAnTMEtZ9pAJWfxQIwEL0zBMmAkAml" + 
			   "ApWfqQCdMwRo8CulAkn/qMiEB70zBDjlAZ0zBLWf6QCVn8UHEBC9MwTJgLAJpQeVn6n/nTMEYLUP" + 
			   "SAqwEmjwA0yCyK0fBykHyQfwDkzMwGgpD6i5DwDQApUPYAMDBgYGBgYGBwcHBQkEBQYICQoGCxBA" + 
			   "sLCAQECAQPDw8KVtOOkEhW2tJQc46QSNJQetGgc46QSNGgetGwc46QSNGwetKgc46QSNKgepAI07" + 
			   "B40rB405B406B7n4m40sB2CtRQfwXq0mB9BZoAuIMFStXwfZa8DQ9a0lB9l2wNDtpc7ZgcDQI6Ud" + 
			   "yQDQHa1fB8kG0CPu2Qbu2gat2gbJA9AerdkGyQPwD9AHrV8HyQbw5iCMwCBx0KkAjdoGjdkGqQCN" + 
			   "RQetzQbwEJUWqQGVD6kAlR6NzQZMJsKsOQex6cn/0ANMFsIpD8kO8A7gBZAKyLHpKT/JLvABYK0d" + 
			   "BxhpMCnwhQetGwdpAIUGrDkHyLHpCpALrTsH0AbuOwfuOgeIsekpD8kP0BmtOwfQFMix6Sk/jToH" + 
			   "7jkH7jkH7jsHTMzArToHlW6x6SnwlYfNHQe1bu0bB7ALsekpD8kO8GlMUMKlB9WHpQb1bpBBqQGV" + 
			   "trHpCgoKCpXPyeDwTMix6SlA8AWtzAbwbbHpKT/JN5AEyT+QMckG0AesagfwAqkClRapAZUPICbC" + 
			   "tQ/QSWCtywbQCa2YA8kB0AupL5UWqQCVHiBswmBMG8fIyLHpSkpKSkrNXwfQDoix6Y1QB8ix6Skf" + 
			   "jVEHTFvCrDkHsekpD8kO0APuOQfuOQfuOQepAI07B6YIYLUWyRWwDai1z2kIlc+pAZ3YA5ggBI4O" + 
			   "ww7DDsMew/DCKMPxwkLDa8PwwnXDdcP3wofH0cdKwz3DhcOgx/DCoMegx6DHoMe4x/DC8MJcxFzE" + 
			   "XMRcxFnE8MLwwvDC8MLfxxLIP8hFyAvIA8gLyEvIV8hJxWC8HrnwwvDC8MLwwvDCB8OByGAgDsNM" + 
			   "RsOpApW2lc9KnZYHSpUeTEbDqbiVz2D49KABrWoH0AGIuQzDlVhMWsMgDsOpAZUeYIBQqQCdogOV" + 
			   "WKzMBrkmw52WB6kLTFzDqQBMGcOpAJVYqQnQEqAwtc+dAQQQAqDgmHXPlVipA52aBKkClUapAJWg" + 
			   "nTQEYKkClUapCZ2aBGAgRsO9pwcpEJVYtc+dNARgrcsG0AupAI3RBiA9w0zZx0yYySYsMjggIiQm" + 
			   "ExQVFq2PB9A84AWwOKmAjY8HoAS5FgDJEfAriBD27tEGrdEGyQeQHaIEtQ/wBcoQ+TAQqQCVHqkR" + 
			   "lRYgisOpICDYxaYIYKXOySyQ+bkeAND0uW4AlW65hwCVh6kBlba5zwA46QiVz72nBykDqKICuZjD" + 
			   "lQHIyMjIyhD0pgggbM+kV8AIsA6ovagHKQPwBZhJ/6jImCBGw6AClVjJADABiJRGqf2VoKkBlQ+p" + 
			   "BZUeYCg4KDgoAAAQEAAgdcWpAJVYtRY46RuouU/EnYgDuVTElTS1zxhpBJXPtYcYaQSVh7VuaQCV" + 
			   "bkzZx4AwQIAwUFBwIECAoHBAkGgOBQYOHCAQDB4iGBQQYCBIrY8H0KEgRsO9qAcpA6i5pMSNjweg" + 
			   "A63MBvAByIQA5ACwhL2nBykDhQCFAan7laCpAKRX8AepBMAZkAEKSBhlAIUAvagHKQPwB72pBykP" + 
			   "hQBoGGUBqLmYxJVYqQGVRqVX0BKkAJgpAvALtVhJ/xhpAZVY9kaYKQLwD6WGGHmIxJWHpW1pAEw8" + 
			   "xaWGOPmIxJWHpW3pAJVuqQGVD5W2qfiVz2AgdcWOaAOpAI1jA41pA7WHjWYDqd+NkAeVRqkgjWQD" + 
			   "nYoHqQWNgwRKjWUDYKD/yLkPAND6jM8GigmAmQ8AtW6ZbgC1h5mHAKkBlQ+ZtgC1z5nPAGCQgHCQ" + 
			   "/wGtjwfQ9J00BKX9CQKF/axoA7kWAMkt8DEg2dEYaSCszAbwAzjpEI2PB72nBykDnRcEqLmdxZXP" + 
			   "rR0HGGkglYetGwdpAJVuTB/GuYcAOOkOlYe5bgCVbrnPABhpCJXPvacHKQOdFwSouZ3FoADVz5AB" + 
			   "yLmhxZ00BKkAjcsGqQidmgSpAZW2lQ9KnQEElR5gADBgYAAgYEBwQGAwrY8H0EepII2PB87XBqAG" + 
			   "iLkWAMkx0Pi5hwA46TBIuW4A6QCFAK3XBhh5HgCoaBh5McaVh6UAaQCVbrk3xpXPqQGVtpUPSpVY" + 
			   "qQiVoGABAgQIECBAgEAwkFAgYKBwCgutjwfQb61OB9BX4AOwZqAAvacHyaqQAcitXwfJAfAByJgp" + 
			   "Aai5msaVFq3dBsn/0AWpAI3dBr2nBykHqLmKxizdBvAHyJgpB0zWxg3dBo3dBrmSxiDYxZ0XBKkg" + 
			   "jY8HTGzCoP/IwAWwDbkPAPD2uRYAyQjQ72Cl/gkIhf6pCNCooAA46TdIyQSwC0igBq1qB/ACoAJo" + 
			   "hAGgsCkC8AKgcIQArRsHhQKtHQeFA6ACaEqQAciM0wai/+jgBbAttQ/Q96UBlRalApVupQOVhxhp" + 
			   "GIUDpQJpAIUCpQCVz6kBlbaVDyBsws7TBtDMTF7CqQGVWEqVHpWgtc+dNAQ46RidFwSpCUzbx7UW" + 
			   "jcsGOOkSIASOpMO3x6jEo8U9xpzGYKAFuRYAyRHQBakBmR4AiBDxqQCNywaVD2CpApVGqfiVWKkD" + 
			   "nZoEYNbP1s+szAbQBaACIHHIoP+toAOVHhACiqiMoAOpAJVGqCBxyKn/naIDTCjIqQCVWEwoyKBA" + 
			   "tc8QB0n/GGkBoMCdAQSYGHXPlVggY8OpBaxOB8AD8AeszAbQAqkGnZoEYCBLyExIyCBXyEwryKkQ" + 
			   "nTQEqf+VoExgyKnwnTQEqQCVoKABIHHIqQSdmgRgCAz4AAD/tYcYeWvIlYe1bnluyJVuYGCmCKkA" + 
			   "tBbAFZADmOkUIASO4Mg1yZXS1sjWyNbI1shHyUfJR8lHyUfJR8lHyUfJ1shlyWXJZcllyWXJZcll" + 
			   "yU3JTcll0IW8S7nWyNnSurjWyKS318hgIK/xIFLxTH3oqQCdxQMgr/EgUvEgfeggQ+Igwd8gM9og" + 
			   "U9isRwfQAyAFyUx61rUWIASOd8p3ynfKd8p3ytjJd8qJyzbMNMlKzErMsMmw0/nK/8olyyjPd8o0" + 
			   "yd/OYCDr0SCv8SBS8SBD4iBT2Ex61iA8zUx61iCv8SBS8SBM4iB72yBS8SBm7SBV1kx61iCv8SBS" + 
			   "8SBz4iBF261HB9ADIILJIFLxIMjlTHrWtRY46SQgBI4y1NPVT9ZP1gfWMdY91qkAlQ+VFpUenRAB" + 
			   "nZYHnSUBncUDnYoHYL2WB9AWIPfCvagHCYCdNAQpDwkGnZYHqfmVoEySvzAcAOgAGAj4DPS1Hikg" + 
			   "8ANM5cq1PPAt1jyt0QMpDNBqvaID0BeszAa5zsmdogMglLqQCbUeCQiVHkxYyt6iA0xYyiA3tR4p" + 
			   "B8kB8D6pAIUAoPq1zzAToP3JcOYAkAvGAL2oBykB0AKg+pSgtR4JAZUepQA9qQeorcwG0AGouRDK" + 
			   "nYoHvagHCcCVPKD8pQkpQNACoASUWKABIEPhMArIvZYH0ASp+JVYlEagALUeKUDQGbUeCrAwtR4p" + 
			   "INBbtR4pB/AkyQXwBMkDsDAgY7+gALUeyQLwDClA8A21Fsku8AfQA0wCv6ABtVhIEALIyBh50MmV" + 
			   "WCACv2iVWGC9lgfQHpUepQkpAajIlEaIrWoH8ALIyLnUyZVYYCBjv0wCv8kO0Am1FskG0AMgmMlg" + 
			   "IJK/TAK/taAdNATQE50XBLXP3QEEsAmlCSkH0AL2z2C1z9VYkANMdb9McL8gRcsgZsugAaUJKQPQ" + 
			   "EaUJKUDQAqD/hAC1zxhlAJXPYKkThQGlCSkD0A20WLWgSrAKxAHwA/ZYYPagYJjw+tZYYLVYSKAB" + 
			   "taApAtALtVhJ/xhpAZVYoAKURiACv4UAaJVYYD8DtR4pINBNrMwGvagHOYfL0BKKSpAEpEWwCKAC" + 
			   "IEPhEAGIlEYg38u1zzj9NATJIJAClc+0RojQDrWHGHVYlYe1bmkAlW5gtYc49ViVh7Vu6QCVbmBM" + 
			   "jL+1oCkC0DelCSkHSLWgSrAVaNARvTQEGGkBnTQElVjJAtAC9qBgaNAUvTQEOOkBnTQElVjQB/ag" + 
			   "qQKdlgdgvZYH8AilCUqwAvbPYLXPaRDFzpDwqQCVoGC1Hikg8ANMkr+p6JVYTAK/QIAEBLUeKSDw" + 
			   "A0yMv4UDtRY46QqouUbMhQK9AQQ45QKdAQS1h+kAlYe1bukAlW6pIIUC4AKQSbVYyRCQFr0XBBhl" + 
			   "Ap0XBLXPZQOVz7W2aQBMrMy9FwQ45QKdFwS1z+UDlc+1tukAlbagALXPOP00BBAHoBBJ/xhpAckP" + 
			   "kAOYlVhgAAEDBAUGBwcIAAMGCQsNDg8QAAQJDRATFhcYAAYMEhYaHR8gAAcPFhwhJScoAAkSGyEn" + 
			   "LC8wAAsVHycuMzc4AAwYJC01Oz5AAA4bKDI7QkZIAA8fLThCSk5QABEiMT5JUVZYAQMCAAAJEhsk" + 
			   "LTY/SFFaYwwYIK/xrdEDKQjQdK1HB9AKvYgDIBDUKR+VoLWgtBbAH5ANyQjwBMkY0AUYaQGVoIXv" + 
			   "IFLxII7OvOUGrbkDmQAChQetrgOZAwKFBqkBhQAgCM6gBbUWyR+QAqALhO2pAIUApe8gjs4gu82l" + 
			   "AMkE0Aiszwa55QaFBuYApQDF7ZDiYKUDhQWkBqUBRgWwBEn/aQEYba4DmQMChQbNrgOwCa2uAzjl" + 
			   "BkzmzTjtrgPJWZAEqfjQFa25A8n48A6lAkYFsARJ/2kBGG25A5kAAoUHIO3smEitnwcNRwfQcIUF" + 
			   "pLWI0Gmkzq1UB9AFrRQH8AnmBeYFmBhpGKiYOOUHEAVJ/xhpAckIsBylBsnwsBatBwIYaQSFBDjl" + 
			   "BhAFSf8YaQHJCJATpQXJAvAjpAWlzhh5Os3mBUwyzqIBpQTFBrAB6IZGogClAEggLNlohQBoGGkE" + 
			   "hQamCGBIKQ/JCZAFSQ8YaQGFAaQAuS7NGGUBqLnHzIUBaEgYaQgpD8kJkAVJDxhpAYUCpAC5Ls0Y" + 
			   "ZQKoucfMhQJoSkpKqLkqzYUDYPigcL0AICAgAAC1Hikg8AipAJ3FA0ySvyACv6ANqQUglr+9NARK" + 
			   "SkpKqLXPOPnVzhAFSf8YaQHJCLAOvTQEGGkQnTQESkpKSqi52s6dxQNgFTBAtR4pIPADTGO/tR7w" + 
			   "C6kAlaCNywapENATqRKNywagArklz5kBAIgQ9yBsz5VYoAG1oCkB0Aq1WEn/GGkBlVjIlEZMAr+g" + 
			   "ACBD4RAKyKUASf8YaQGFAKUAyTyQHKk8hQC1FskR0BKY1aDwDbWg8AbWWLVY0ECYlaClACk8SkqF" + 
			   "AKAApVfwJK11B/AfyKVXyRmQCK11B8kCkAHItRbJEtAEpVfQBrWg0AKgALkBAKQAOOkBiBD6YBpY" + 
			   "mJaUkpCOjIqIhoSCgK5oA7UWyS3QEIYItR7wGilA8Aa1z8ngkAqpgIX87nIHTHHQIIy/THvRzmQD" + 
			   "0ESpBI1kA61jA0kBjWMDqSKFBaxpA7ndz4UErAADyKIMIM2Kpgggj4qpCIX+qQGF/e5pA61pA8kP" + 
			   "0AsgY8OpQJUeqYCF/kx70SFBETG1Hikg8BS1z8ngkJ6iBCCYycoQ+o3LBqYIYKkAjcsGrUcH8ANM" + 
			   "OdGtYwMQA0wP0c5kA9ANqSCNZAOtYwNJAY1jA6UJKQ/QBKkClUa9igfwHCBD4RAXqQGVRqkCjWUD" + 
			   "qSCdigeNkAe1h8nIsD6lCSkD0Di1h81mA9AMvacHKQOouWHQjdwGtYcYbWUDlYe0RsAB8Beg/zjt" + 
			   "ZgMQB0n/GGkBoAHN3AaQA4xlA72KB9AoIIy/rV8HyQWQCaUJKQPQAyCUurXPyYCQHL2nBykDqLlh" + 
			   "0J2KB0xJ0ckB0AnWzyBjw6n+laCtXwfJB/AEyQWwJ62QB9AiqSCNkAetYwNJgI1jAzDhINnRrMwG" + 
			   "8AM46RCNkAepFY3LBiC80aAQtUZKkAKg8JgYdYeszwaZhwC1zxhpCJnPALUemR4AtUaZRgClCEiu" + 
			   "zwaGCKktlRYgvNFohQiqqQCNagNg7moDINfItR7Q9akKnZoEIEPiTFPYv0C/v79AQL+sZwPuZwOt" + 
			   "ZwMpB41nA7nR0WCtRwfQMKlArMwG8AKpYIUAvQEEOOUAnQEEtYfpAZWHtW7pAJVuvBcEtc/ZncXw" + 
			   "Bhh9NASVzyBS8bUe0MOpUYUAoAKlCSkC8AKggoQBvOUGogCtuQOZAAKlAJkBAuYApQGZAgKtrgOZ" + 
			   "AwIYaQiNrgPIyMjI6OADkNmmCCCv8bzlBq3RA0pIkAWp+JkMAmhKSJAFqfiZCAJoSkiQBan4mQQC" + 
			   "aEqQBan4mQACYNag0AypCJWg9li1WMkDsBggUvGtuQONugOtrgONrwO85Qa1WCAX7WCpAJUPqQiF" + 
			   "/qkFjTgBTDbTAAAICAAIAAhUVVZXqQCNywatRgfJBbAsIASOEdPy0hLTTtOi06AFrfoHyQHwDqAD" + 
			   "yQPwCKAAyQbwAqn/jdcGlB7uRgdgrfgHDfkHDfoH8PGlCSkE8ASpEIX+oCOp/405ASBfj6kFjTkB" + 
			   "oAutUwfwAqARIF+PrVMHCgoKCgkETDa8tc/JcpAF1s9MZdOt1wbwODA2qRaNywYgUvG85QaiA625" + 
			   "Axh9zdKZAAK91dKZAQKpIpkCAq2uAxh90dKZAwLIyMjIyhDapghgIGXTqQadlgfuRgdgIGXTvZYH" + 
			   "0AWtsQfw72C1HtBWvYoH0FG1oNAjtVgwFCBD4RAJpQBJ/xhpAYUApQDJIZA1tVhJ/xhpAZVY9qC9" + 
			   "NAS0WBADvRcEhQClCUqQGa1HB9AUtc8YdViVz8UA0AmpAJWgqUCdigepIJ3FA2CFB7U00A6gGLVY" + 
			   "GGUHlVi1oGkAYKAItVg45QeVWLWg6QBgtbbJA9ADTJjJtR4QAWCovaIDhQC1RvADTLvVqS3Vz5AP" + 
			   "xADwCBhpApXPTLHVTJjV2c8AkA3kAPD0GGkCmc8ATLHVtc9IvaIDEBi9NAQYaQWFALWgaQAwGtAM" + 
			   "pQDJC5AMsATFCPAMILe/TKfUILHVTKfUILS/tB5oOPXPGHnPAJnPAL2iAzAEqiAh3KQIuaAAGTQE" + 
			   "8HeuAAPgILBwuaAASEggQdWlAZ0BA6UAnQIDqQKdAwO5oAAwDaminQQDqaOdBQNM/9SpJJ0EA50F" + 
			   "A7keAKhoSf8gQdWlAZ0GA6UAnQcDqQKdCANoEA2pop0JA6mjnQoDTDDVqSSdCQOdCgOpAJ0LA60A" + 
			   "AxhpCo0AA6YIYEi5hwAYaQiuzAbQAxhpEEi5bgBpAIUCaCnwSkpKhQC2z2gQBYoYaQiqiq4AAwoq" + 
			   "SCopAwkghQGlAikBCgoFAYUBaCngGGUAhQC5zwDJ6JAGpQApv4UAYJiqIK/xqQYgEdqtrQOdFwGl" + 
			   "zp0eAakBlUYgY8OZoACZNARgmEgga79oqiBrv6YIvaIDMASqICHcpghgtaAdNATQFZ0XBLXP3QEE" + 
			   "sAulCSkH0AL2z0z+1bXP1ViQBiC3v0z+1SC0v72iAzADICHcYKkOIEfLIGbLvaIDMBylhhhlAIWG" + 
			   "pW2kADAFaQBMKNbpAIVtjKEDICHcYL2iAzAGIIi/ICHcYCACv4UAvaIDMAepEJVYIBTWYCBb1kz+" + 
			   "1SBb1kxx1q1HB9AZvRcEGH00BJ0XBLXPdaCVz2C9ogPwAyAZ3GC1FskU8FWtHAe0FsAF8ATADdAC" + 
			   "aTjpSIUBrRoH6QCFAK0dB2lIhQOtGwdpAIUCtYfFAbVu5QAwILWHxQO1buUCMBm1HskF8BPADfAP" + 
			   "wDDwC8Ax8AfAMvADIJjJYP///7Uk8FYKsFOlCUqwTooKChhpHKiiBIYBmEi1Hikg0DS1D/AwtRbJ" + 
			   "JJAEySuQJskG0Aa1HskCsBy92APQF4oKChhpBKogJ+OmCJAJqYCVJKYBID7XaKimAcoQu6YIYAYA" + 
			   "AhIRBwUtIFLxpgG1DxALKQ+qtRbJLfAMpgG1FskC8GvJLdAtzoME0GIgY8OVWI3LBqn+laCsXwe5" + 
			   "NteVFqkgwAOwAgkDlR6pgIX+pgGpCdAzyQjwNskM8DLJFbAutRbJDdAGtc9pGJXPIBvgtR4pHwkg" + 
			   "lR6pArQWwAXQAqkGwAbQAqkBIBHaqQiF/2ClCUqQNq1HBw3WA9AuigoKGGkkqCAl46YIkBu9vgbQ" + 
			   "G6kBnb4GtWRJ/xhpAZVkrZ8H0AhMLNmpAJ2+BmAgmMmpBiAR2qkghf6lOckCkA7JA/AkqSONnwep" + 
			   "QIX7YK1WB/AbyQHQI6YIqQKNVgcg8YWmCKkMTEfYqQudEAFgqQGNVgepCaAAIEjZYBjoMNAI+KUJ" + 
			   "SrD0IEHcsCO92APQHqUOyQjQGLUeKSDQEiBS3CAl46YIsAm9kQQp/p2RBGC0FsAu0ANMANitnwfw" + 
			   "BkyV1woGBL2RBCkBHdgD0FmpAR2RBJ2RBMAS8E7ADfB9wAzwecAz8ELAFbBxrU4H8Gy1HgqwNLUe" + 
			   "KQfJApAstRbJBvAlqQiF/7UeCYCVHiAF2rlP2JVYqQMYbYQEvJYHwAOwA7mS2CAR2mClnzAC0Gq1" + 
			   "FskHkAmlzhhpDNXPkFutkQfQVq2eB9A9ra0Dza4DkANM9tm1RskB0ANM/9mtngfQJK5WB/AijVYH" + 
			   "qQiNngcKhf8g8YWpCqABhQ6EHaD/jEcHyIx1B6YIYIZX6Ib8qfyFn6kL0OECBgUGtRbJEvC9qQSF" + 
			   "/7UWoADJFPAbyQjwF8kz8BPJDPAPyMkF8ArIyRHwBcjJB9AduWXZIBHatUZIIC/gaJVGqSCVHiBj" + 
			   "w5VYqf2Fn2DJCZAdKQGVFqAAlB6pAyAR2iBjwyAF2rlR2JVYTPHZEAupBJUe7oQErYQEGG2RByAR" + 
			   "2u6RB6xqB7nS2Z2WB6n8hZ9gtUbJAdADTCzZIBzbTCzZoAEgQ+EQAciURohgnRABqTCdLAG1z50e" + 
			   "Aa2uA50XAWCAQCAQCAQCf7/f7/f7/aUJSpDsrU4H8Oe1FskVsG7JEfBqyQ3wZr3YA9BhIFLcyjBb" + 
			   "hgGYSLUP8Ey1FskVsEbJEfBCyQ3wPr3YA9A5igoKGGkEqiAn46YIpAGQILUeGR4AKYDQEbmRBD0l" + 
			   "2tAYuZEEHSXamZEEILTaTKrauZEEPSzamZEEaKimAcoQpaYIYLkeABUeKSDQM7UeyQaQLrUWyQXw" + 
			   "J7keAAqQCqkGIBHaIJXXpAGYqiCV16YIvSUBGGkEpgEgEdqmCP4lAWC5HgDJBpAduRYAyQXw8SCV" + 
			   "16QBuSUBGGkEpgggEdqmAf4lAWCYqiAc26YItRbJDfAiyRHwHskF8BrJEvAIyQ7wBMkHsA61WEn/" + 
			   "qMiUWLVGSQOVRmCp/52iA61HB9AptR4wJbUWySTQBrUeqiBf2yBB3LAUiiBU3LXPhQCKSCAl42iq" + 
			   "kAMgvNumCGCtRwfQN52iAyBB3LAvqQKFAKYIIFLcKQLQIrmtBMkgkAUgJeOwGbmtBBhpgJmtBLmv" + 
			   "BBhpgJmvBMYA0NWmCGCmCLmvBDjtrQTJBLAIpZ8QBKkBhZ+trwQ4+a0EyQawG6WfMBelALQWwCvw" + 
			   "BcAs8AGKpgidogOpAIUdYKkBhQCtrgQ4+awEyQiQDeYAua4EGO2sBMkJsAMgS9+mCGCAAKi1zxh5" + 
			   "Ftwstc+kDsAL8Be0tsAB0BE46SCFzpjpAIW1qQCFn40zBGCt0APJ8LAJpLWI0ASlzsnQYKUICgoY" + 
			   "aQSordEDKQ/JD2AgEK0WB9AupQ7JC/AoyQSQJKkBrAQH0AqlHfAEyQPQBKkChR2ltckB0Aup/42Q" + 
			   "BKXOyc+QAWCgAq0UB9AMrVQH0AeIrQQH0AGIua3jheuorlQHrRQH8AHopc7dYtyQNSDp4/AwIKHf" + 
			   "sE+knxAnpATABJAhII/fsBCsTgfwE6yEB9AOIO28TPbcySbwBKkChf+pAYWfpOulzsnPsGAg6OMg" + 
			   "od+wFEgg6OOFAGiFAdAMpQDwSSCh35ADTAXeIJrfsDyknzA4ycXQA0wO3iC93vAsrA4H0COkBMAF" + 
			   "kAelRYUATEvfIMTeqfAlzoXOIOjeqQCFn40zBI2EBKkAhR2k68jIqQKFAMiE66XOySCQFsnksCgg" + 
			   "7OPwDckc8AnJa/AFIJrfkBek68ilzskIkA3J0LAJIOzj0AXGANDLYCC93vBhIJrfkANMLt4god+w" + 
			   "VyDd3pAIrQ4H0EpM/92kHcAA0D6kM4jQOcls8ATJH9AxrcQD0ASgEIT/CSCNxAOlhikP8A6gAK0a" + 
			   "B/AByLkD3o3eBqUOyQfwDMkI0AipAoUOYCBL32CgNCAc3u5IB0z+u6kAjXIHqQKNcAepGIVXpAKp" + 
			   "AJEGTE2K+Qf/ABgiUGiQpATABpAEwAqQAWDJJPAEySXQOaUOyQXwQakBhTPuIwelDskE8B+pMyAW" + 
			   "l6mAhfxKjRMHogSlzo0PB90p3rADytD4jg8BqQSFDkyI3skm0AqlzskgsASpAYUOqQOFHakAhVeN" + 
			   "BQelhjjtHAfJELAEqQKFM6QzpQYKCgoKGHkk3oWGpQbQCa0bBxh5Jt6FbWDJX/ACyWBgIN3ekBOp" + 
			   "cI0JB6n5jdsGqQONhgdKjQ4HYMln8AXJaBjQAThgpQspBPBcpQDJEdBWpQHJENBQqTCN3gapA4UO" + 
			   "qRCF/6kgjcQDrdYG8DkpAwoKqqWGyWCQBujJoJAB6Lzyh4iMXwe+tJy9vJyNUAepgIX8qQCNUQeN" + 
			   "YAeNXAeNUgfuXQfuVwdgqQCkV6YAytAK6MAAMCip/0xm36ICwAEQHakBoBCMhQegAIRXyQAQAYiE" + 
			   "ABhlhoWGpW1lAIVtikn/LZAEjZAEYBBhiMQgsN/di99gJG2KxiCw392W32DJwvAGycPwAhhgqQGF" + 
			   "/mCoKcAKKiqqmGABAQICAgUQ8LUeKSDQ8SBb4ZDstBbAEtAGtc/JJZDgwA7QA0xj4cAF0ANMheHA" + 
			   "EvAIwC7wBMAHsHQgruHQA0zi4CC14fD4ySPQZKQCqQCRBrUWyRWwDMkG0AMgjuGpASAR2skJkBDJ" + 
			   "EbAMyQqQBMkNkAQpAZUWtR4p8AkClR7Wz9bPtRbJB/AHqf2sTgfQAqn/laCgASBD4RAByLUWyTPw" + 
			   "BskI8AKURoi5v9+VWGClBDjpCMkFsHK1HilA0Fe1HgqQA0z+4LUe8PnJBfAfyQOwGrUeyQLQFakQ" + 
			   "tBbAEtACqQCdlgepA5UeIE/hYLUWyQbwIskS0A6pAZVGqQiVWKUJKQfwEKABIEPhEAHImNVG0AMg" + 
			   "JOEgT+G1HimA0AWpAJUeYLUeKb+VHmC1FskD0AS1HvA4tR6oCpAHtR4JQEz84Lm535Uetc/JIJAf" + 
			   "oBapAoXrpevVRtAMqQEgiOPwBSC14dAIxuvIwBiQ52DgBfAJtR4KkASpAoX/tRbJBdAJqQCFAKD6" + 
			   "TDfKTDbbtYc45YaFALVu5W1gIGPDtc8p8AkIlc9gtc8YaT7JRGAgW+GQGrWgGGkCyQOQESCu4fAM" + 
			   "ILXh8AcgT+Gp/ZWgTP7gIK7h8B3JI9AIIJXXqfyVoGC9igfQDLUeKYiVHiBP4Uz+4LUeCQGVHmCp" + 
			   "AKAVTIjjySbwDsnC8ArJw/AGyV/wAslgYLXVyRiQISCc4/AcILXh8Be1pjAYtTrQFKn9laapAZU6" + 
			   "tdUp+JXVYKkAlTpgqYCVJKkChf9gAggOIAMUDSACFA4gAgkOFQAAGAYAACANAAAwDQAACAgGBAoI" + 
			   "Aw4NFAACEBUEBAwcihhpB6qgAtAHihhpCaqgBiCc4kze4qBIhACgRExS4qAIhACgBLWHOO0cB4UB" + 
			   "tW7tGgcwBgUB8AKkAJgt0QOd2APQGUx84ugg9vHKyf6wDYoYaQGqoAEgnOJM3uKKCgqoqf+ZsASZ" + 
			   "sQSZsgSZswRghgC5uAOFArmtA4UBigoKSKi9mQQKCqqlARh9/eGZrASlARh9/+GZrgToyKUCGH39" + 
			   "4ZmsBKUCGH3/4ZmuBGiopgBgrRwHGGmAhQKtGgdpAIUBtYbFArVt5QGQFbmuBDANqf++rAQwA5ms" + 
			   "BJmuBKYIYLmsBBARyaCQDakAvq4EEAOZrgSZrASmCGCiAIQGqQGFB7msBN2sBLAq3a4EkBLwQrmu" + 
			   "BNmsBJA63awEsDWkBmC9rgTdrASQKrmuBN2sBLAipAZg3awE8BrdrgSQFfAT2a4EkArwCLmuBN2s" + 
			   "BLAEGKQGYOjIxgcQqTikBmBIihhpAapoTKXjihhpDaqgG0yj46AaihhpB6qpACDw46YIyQBgAAcO" + 
			   "CAMMAgINDQgDDAICDQ0IAwwCAg0NCAAQBBQEBAQgIAgYCBgCICAIGAgYEiAgGBgYGBgUFAYGCBDI" + 
			   "qQAsqQGiAEiEBLmw4xh1hoUFtW1pACkBSgUFakpKSiDhm6QEtc4YeczjKfA46SCFAqixBoUDpARo" + 
			   "0AW1zkwr5LWGKQ+FBKUDYP8AMIQArbkDGHkz5L6aA7zlBoQCIK7kra4DmQMCmQsCmRMCGGkGmQcC" + 
			   "mQ8CmRcCqSGZAgKZCgKZEgIJQJkGApkOApkWAqIFqeGZAQLIyMjIyhD0pAKlANAFqeCZAQKiAK2d" + 
			   "Azj5AALJZJAFqfiZAALIyMjI6OAG0OekAGCiBpkAAhhpCMjIyMjK0POkAmAEAAQAAAQABAAIAAgI" + 
			   "AAgAgIKBg4GDgIIDA8PDvPMGrUcH0Ai1Kil/yQHwBKIA8AelCUpKKQOqrb4DGH3E5JkAAhh9zOSZ" + 
			   "BAKtswMYfcDkmQMCGH3I5JkHAr3Q5JkBAr3U5JkFAr3Y5JkCApkGAqYIrdYDKfzwCakAlSqp+CDB" + 
			   "5WD5UPdQ+vv4+/b7vOUGra4DmQMCGGkImQcCmQsCGGkMhQW1zyDB5WkImQgCrQ0BhQKpAYUDhQSZ" + 
			   "AgKZBgKZCgKpfpkBApkJAql/mQUCrQ8H8BWYGGkMqK0PAQqqvUHlhQC9QuUgsuumCLzlBq3RAykO" + 
			   "8BSp+JkUApkQApkMApkIApkEApkAAmC85QaEAsjIyK2uAyCu5KYItc8gu+WsTgfAA/AFrMwG8AKp" + 
			   "+LzlBpkQApkUAqlbrkMH8AKpdaYIyCC15akCyCC15egg9vHKvOUGCkiQBan4mQACaApIkAWp+JkE" + 
			   "AmgKSJAFqfiZCAJoCkiQBan4mQwCaApIkAWp+JkQAmgKkAWp+JkUAq3RAwqQAyCz5WClCUqwAtbb" + 
			   "tdsgweWtswOZAwIYaQiZBwKpApkCApkGAqn3mQECqfuZBQJMveZgYWJjvPMGtSrJArDGtduZAAIY" + 
			   "aQiZBAKtswOZAwKZBwKlCUopA6q9gubIIMHliKkCmQICqYKZBgKmCGB2d3h51tbZ2Y2N5OR2d3h5" + 
			   "AgECAazqBq25AxhpCIUCra4DhQWmOb3O5g3KA4UEikgKCqqpAYUHhQO9vuaFAL2/5iCy68YHEPGs" + 
			   "6gZo8C/JA/ArhQClCUopAw3KA5kCApkGAqYAyvAGmQoCmQ4CuQYCCUCZBgK5DgIJQJkOAkxk6/z8" + 
			   "qqusrfz8rq+wsfylpqeoqfygoaKjpGmlaqeoqWugbKKjpPz8lpeYmfz8mpucnfz8j46Oj/z8lZSU" + 
			   "lfz83Nzf39zc3d3e3vz8srO0tfz8trO3tfz8cHFyc/z8bm5vb/z8bW1vb/z8b29ubvz8b29tbfz8" + 
			   "9PT19fz89PT19fz89fX09Pz89fX09Pz8/Pzv77m4u7q8vPz8vb28vHp72tvY2M3Nzs7Pz3180YzT" + 
			   "0n18iYiLitXU4+LT0tXU4+KLiuXl5ubr6+zs7e3u7vz80NDX17++wcDC/MTDxsXIx7++ysnC/MTD" + 
			   "xsXMy/z86Ofq6fLy8/Py8vHx8fH8/PDw/Pz8/AwMAAwMqFQ86hhISMzAGBgYkCT/SJzS2PD2/AEC" + 
			   "AwIBAQMDAwEBAgIhAQIBAQL/AgIBAQICAggYGBkaGRi1z4UCra4DhQW85QaE66kAjQkBtUaFA73F" + 
			   "A4UEtRbJDdAKtFgwBryKB/ABYLUehe0pH6i1Fsk10AigAKkBhQOpFckz0BPGAqkDvIoH8AIJIIUE" + 
			   "oACE7akIyTLQCKADrg4HvXjohe+E7KYIyQzQB7WgMAPuCQGtagPwCaAWyQHwAciE76TvwAbQHbUe" + 
			   "yQKQBKIEhuwpIA1HB9AMpQkpCNAGpQNJA4UDuVvoBQSFBLlA6Kqk7K1qA/AwyQHQE61jAxACot6l" + 
			   "7Skg8AOOCQFMS+qtYwMpAfACouSl7Skg8O6lAjjpEIUCTEbp4CTQEcAF0AqiMKkChQOpBYXsTMrp" + 
			   "4JDQEqXtKSDQCa2PB8kQsAKilkw36qXvyQSwEMACkAyiWqTvwALQBKJ+5gKl7MkE0B6icuYCpO/A" + 
			   "AvAEombmAsAG0AyiVKXtKSDQBKKKxgKkCKXvyQXQDKXt8CQpCPBdorTQHOBI8Bi5lgfJBbBO4DzQ" + 
			   "DckB8EbmAuYC5gJMKeql78kG8DfJCPAzyQzwL8kYsCugAMkV0BDIrV8HyQewHaKiqQOF7NAVpQk5" + 
			   "dujQDqXtKaANRwfQBYoYaQaqpe0pIPAOpe/JBJAIoAGMCQGIhOyk6yCq6yCq6yCq66YIvOUGpe/J" + 
			   "CNADTGTrrQkB8D25AgIJgMjIILXliIiYqqXvyQXwDckR8AnJFbAFihhpCKq9AQJIvQUCSLkRAp0B" + 
			   "ArkVAp0FAmiZFQJomRECrWoD0Lal76bsyQXQA0xk68kH8B3JDfAZyQzwFckS0ATgBdBIyRXQBalC" + 
			   "mRYC4AKQO61qA9A2uQICKaOZAgKZCgKZEgIJQOAF0AIJgJkGApkOApkWAuAE0BO5CgIJgJkKApkS" + 
			   "AglAmQ4CmRYCpe/JEdA2rQkB0CG5EgIpgZkSArkWAglBmRYCro8H4BCwMJkOAimBmQoCkCa5AgIp" + 
			   "gZkCArkGAglBmQYCpe/JGJAQqYKZCgKZEgIJQJkOApkWAqYIrdEDSkpKSJAFqQQgwetoSkiQBakA" + 
			   "IMHraEpKSJAFqRAgt+toSkiQBakIILfraEqQEiC367UWyQzwCbW2yQLQAyCYyWC9PueFAL0/54UB" + 
			   "TILyGH3lBqip+EzB5Rh95QaoIErsmRACYIWFhoatvAOFAq2xA4UFqQOFBEqFA7zsBqIAvc3rhQC9" + 
			   "zusgsuvgBNDxpgi87AatTgfJAfAIqYaZAQKZBQK96APJxNAkqYfIILvliKkDrk4HyvABSqYImQIC" + 
			   "CUCZBgIJgJkOAimDmQoCrdQDSCkE8Aip+JkEApkMAmgpCPAIqfiZAAKZCAJgqQKFAKl1pA7ABfAG" + 
			   "qQOFAKmEvOwGyCC75aUJCgoKCinABQDIILvliIitvAMgweWtsQOZAwK98QM47RwHhQA47bEDZQBp" + 
			   "BpkHAq29A5kIApkMAq2yA5kLAqUAOO2yA2UAaQaZDwKt1AMgRuyt1AMKkAWp+CDB5aUAEBC5AwLZ" + 
			   "BwKQCKn4mQQCmQwCYLzxBq26A5kAAq2vA5kDAqUJSkpIKQFJZJkBAmhKSqkCkAIJwJkCAmBoZ2a8" + 
			   "7Aa1JPYkSikHyQOwSqq9Bu3IILvliKYIrboDOOkEmQACmQgCGGkImQQCmQwCra8DOOkEmQMCmQcC" + 
			   "GGkImQsCmQ8CqQKZAgKpgpkGAqlCmQoCqcKZDgJgqQCVJGC85QapW8ggteXIqQIgteWIiK2uA5kD" + 
			   "ApkPAhhpCJkHApkTAhhpCJkLApkXArXPqkjgILACqfggvuVoGGmAquAgsAKp+JkMApkQApkUAq3R" + 
			   "A0gpCPAIqfiZAAKZDAJoSCkE8Aip+JkEApkQAmgpAvAIqfiZCAKZFAKmCGCktYjQIK3TAykI0Bm8" + 
			   "7gatsAOZAwKtuwOZAAKpdJkBAqkCmQICYCAoyBgAQFBYgIi4eGCgsLgAAQIDBAUGBwgJCgsMDQ4P" + 
			   "EBESExQVFhcYGRobHB0eHyAhIiMkJSYnCAkoKSorLC0ICQoLDDAsLQgJCgsuLywtCAkoKSorXF0I" + 
			   "CQoLDA1eX/z8CAlYWVpaCAkoKSorDg/8/Pz8MjM0Nfz8/Pw2Nzg5/Pz8/Do3Ozz8/Pz8PT4/QPz8" + 
			   "/PwyQUJD/Pz8/DIzREX8/Pz8MjNER/z8/PwyM0hJ/Pz8/DIzkJH8/Pz8OjeSk/z8/Pyenp+f/Pz8" + 
			   "/Do3T0/8/AABTE1OTgABTE1KSktLMUatngfwBaUJSrBApQ7JC/BHrQsH0DysBAfwMaUdyQDwKyA0" + 
			   "76UJKQTQIaqs5AalM0qwBMjIyMitVAfwCbkZAs217vAH6L3n7pkZAmAg7O9MRe8gsPBMRe+gDrkH" + 
			   "7o3VBqkEIL7vIOnwrREH8CWgAK2BB80RB4wRB7AYjREHoAe5B+6N1QagBKVXBQzwAYiYIL7vrdAD" + 
			   "SkpKSoUAogOt5AYYaRioqfhGAJADIMHlmDjpCKjKEO9gWAEAYP8EogW9nu+VAsoQ+KK4oAQg3O+t" + 
			   "JgIJQI0iAmCFB62tA41VB4UFrbgDhQKlM4UDrcQDhQSu1Qas5Aa9F+6FAL0Y7iCy68YH0PFgpR3J" + 
			   "A/BSyQLwPskB0BGtBAfQUaAGrRQH0CKgAEwo8KAGrRQH0BagAqVXBQzwDq0AB8kJkBulRSUz0BXI" + 
			   "IJHwqQCNDQe5B+5goAQgkfBMYvCgBCCR8Exo8KAFpZ/w3iCR8Ext8KABIJHwrYIHDQ0H0AulCgqw" + 
			   "Bq0NB0zQ8KkDTG/wqQKFACBi8EitgQfQFa0MB42BB60NBxhpAcUAkAKpAI0NB2hgrVQH8AWYGGkI" + 
			   "qGAAAQABAAECAAECAgACAAIAAgACAKwNB6UJKQPQDcjACpAFoACMCweMDQetVAfQDLmc8KAPCgoK" + 
			   "eQfuYJgYaQqqoAm9nPDQAqABuQfuYKzkBqUOyQvwE63VBslQ8B7JuPAaycDwFsnI0CS5EgIpP5kS" + 
			   "ArkWAik/CUCZFgK5GgIpP5kaArkeAik/CUCZHgJgogCgAExC8aABIKjxoANMQvGgACCo8aACIHHx" + 
			   "pghgoAIgqPGgBkxC8akBoAFMZfGpCaAEIGXx6OipCciGABhlAKogcfGmCGC1zpm4A7WGOO0cB5mt" + 
			   "A2CiAKAATMDxoAAgqPGgAkzA8aABIKjxoANMwPGgAiCo8aAGTMDxBxYNihh5pfGqYKkBoAFMuvGp" + 
			   "CaAEhgAYZQCqmEgg1/EKCgoKBQCFAGiopQCZ0AOmCGAg9vFKSkpKhQBMOfJ/Px8PBwMBAIDA4PD4" + 
			   "/P7/Bw8HhgSgAbkcBzj1hoUHuRoH9W2+8/HJADAQvvTxyQEQCak4hQapCCBt8r3j8aYEyQDQA4gQ" + 
			   "0GAACAwODwcDAQAEAAT/AIYEoAG5N/I49c6FB6kB9bW+NPLJADAQvjXyyQEQCakghQapBCBt8r0r" + 
			   "8qYEyQDQA4gQ0WCFBaUHxQawDEpKSikHwAGwAmUFqmClA0pKpQCQDJkFAqUBmQECqUDQCpkBAqUB" + 
			   "mQUCqQAFBJkCApkGAqUCmQACmQQCpQWZAwIYaQiZBwKlAhhpCIUCmBhpCKjo6GD///////+tcAfQ" + 
			   "BI0VQGCp/40XQKkPjRVArcYH0Aal+skB0F2tsgfQI6X68GaNsgeNxgepAI0VQIXxhfKF86kPjRVA" + 
			   "qSqNuwepRNARrbsHySTwCMke8PHJGNAJqWSihKB/IIjzzrsH0CqpAI0VQK2yB8kC0AWpAI3GB6kA" + 
			   "jbIH8BIgG/QgfPUgZ/YglPapAIX7hfypAIX/hf6F/YX6rMAHpfQpA/AH7sAHwDCQBpjwA87AB4wR" + 
			   "QGCMAUCOAEBgIIHzogCouQH/8AudAkC5AP8JCJ0DQGCOBECMBUBgIJ/zogTQ4KII0Nyfm5iWlZSS" + 
			   "kJCal5WTkqlAjbsHqWIgi/OimdAlqSbQAqkYooKgpyCI86kojbsHrbsHySXQBqJfoPbQCMkg0Cmi" + 
			   "SKC8IIHz0CCpBaCZ0ASpCqCTop6NuwepDCCI8627B8kG0AWpu40BQNBgpP/wIITxMKpG/7CqRv+w" + 
			   "1Eb/sCxG/7BKRv+wf0b/sL5G/7CApfHwFzCaSrCXSrDCSrAbSrA8SrBnSrC2SrBIYKkOjbsHoJyi" + 
			   "nqkmIIjzrLsHubDzjQBAwAbQBamejQJA0CWpDqDLop+NuwepKCCI89AVrLsHwAjQCamgjQJAqZ/Q" + 
			   "AqmQjQBAzrsH0A6iAIbxog6OFUCiD44VQGCpL427B627B0qwEEqwDSkC8AmgkaKaqUQgiPNMovRY" + 
			   "AlRWTkRMUkxIPjY+NjAoSlBKZDwyPDIsJDpkOjQsIiwiHBQUBCIkFgQkJhgEJigaBCgqHAQqLB4E" + 
			   "LC4gBC4wIgQwMqk1oo3QBKkGopiNvQegf6lCIKbzrb0HyTDQBalUjQZA0C6pII29B6CUqV7QC629" + 
			   "B8kY0Bygk6kY0H+pNo29B629B0qwC6i52fSiXaB/IKbzzr0H0A6iAIbyog2OFUCiD44VQGCl8ilA" + 
			   "0GWk/vAghPIwPkb+sIpG/rBqRv6wakb+sKBG/rCARv6wsEb+sDyl8vAXMCdKsBNKsF1KsFpKsI1K" + 
			   "sAdKsJlKsCZgTCz1TGj1qTiNvQegxKkY0AutvQfJCNCOoKSpWqKf0IOpMI29B629B6IDSrDWytD6" + 
			   "qLnT9KKCoH/Q5KkQ0AKpII29B6l/jQVAqQCNvgfuvgetvgdKqMy9B/AMqZ2NBEC5+PQgqfNgTG31" + 
			   "AQ4ODQsGDA8KCQMNCA0GDKkgjb8Hrb8HSpASqL4r9rnq/40MQI4OQKkYjQ9Azr8H0Amp8I0MQKkA" + 
			   "hfNgpP3wCoTzRv2wykb9sAul8/AGSrDESrAGYKlAjb8Hrb8HSqiiD7nJ/9C8TDr3pfzQDKX70Cyt" + 
			   "sQcF9NDuYI2xB8kB0AYgp/QgcfWm9I7FB6AAjMQHhPTJQNAwogiOxAfQKckE0AMgp/SgEIzHB6AA" + 
			   "jLEHhfTJAdAO7scHrMcHwDLQDKAR0OSgCIT3yEqQ/LkM+ai5DfmF8LkO+YX1uQ/5hfa5EPmF+bkR" + 
			   "+YX4uRL5jbAHjcEHqQGNtAeNtgeNuQeNugepAIX3jcoHqQuNFUCpD40VQM60B9BfpPfm97H18AQQ" + 
			   "PdAvrbEHyUDQBa3FB9AdKQTQHKX0KV/QE6kAhfSNsQeNCECpkI0AQI0EQGBM1PZMpPYgy/iNswek" + 
			   "9+b3sfWm8tAOIKnz8AMg2PiNtQcgn/OtsweNtAel8tAarbEHKZHQE6y1B/ADzrUHIPT4jQRAon+O" + 
			   "BUCk+PBazrYH0DKk+Ob4sfXQD6mDjQBAqZSNAUCNygfQ6SDF+I22B6Tx0DSKKT4gi/PwAyDY+I23" + 
			   "ByCB86Xx0B+tsQcpkdAOrLcH8APOtwcg9PiNAECtygfQAql/jQFApfnOuQfQTKT55vmx9fBBEBMg" + 
			   "y/iNuAepH40IQKT55vmx9fAsIK3zrrgHjrkHrbEHKW7QBqX0KQrwGYrJErAPrbEHKQjwBKkP0Aap" + 
			   "H9ACqf+NCECl9Cnz8FHOugfQTKywB+6wB7H10AitwQeNsAfQ7iDF+I26B4opPvAkyTDwGMkg8Awp" + 
			   "EPAYqRyiA6AY0BKpHKIMoBjQCqkcogOgWNACqRCNDECODkCMD0BgqmqKKioqKQcYZfBtxAeouWb/" + 
			   "YK2xBykI8ASpBNAMpfQpffAEqQjQAqkoooKgf2CtsQcpCPAEuZb/YKX0KX3wBLma/2C5ov9gpVlU" + 
			   "ZFk8MUtpXkZPNo02S41paW91b3tvdW97gYeBjWlpk5mTn5OZk5+Bh4GNk5mTnwhy/CcYILj5LhpA" + 
			   "ILD8PSEgxPw/HRgR/QAACBz6AACk+5NiEMj+JBQYRfweFAhS/aBwaAhR/kwkGAH6LRy4GEn6IBJw" + 
			   "GHX6GxBEGJ36EQocGML6LRBYGNv6FA0/GPn6FQ0hGCX7GBB6GEv7GQ9UGHT7HhIrGHL7Hg8thCws" + 
			   "LIIELASFLIQsLCoqKoIEKgSFKoQqKgAfHx+YHx+YnpgfHR0dlB0dlJyUHYYYhSYwhAQmMIYUhSIs" + 
			   "hAQiLCHQxNAx0MTQAIUsIhyEJiqCKCYEhyI0OoJABDaEOjSCLDCFKgBdVU0VGZYV1ePrLaYrJ5ye" + 
			   "WYUiHBSEHiKCIB4EhxwsNII2BDA0BCwEJiqFIoQEgjo4NjIENAQkJiwEJiwwAAW0srArrIScnqKE" + 
			   "lJyehRQihCyFHoIshCwehASCOjg2MgQ0BGQEZIZkAAW0srArrIQ3trZFhRQcgiKELE6CToROIoQE" + 
			   "hTKFMIYsBAAFpAWeBZ2FhBSFJCgsgiKEIhQh0MTQMdDE0ACCLIQsLIIsMAQ0LAQmhiIApCUlpCmi" + 
			   "HZyVgiwsBCwELDCFNAQEAKQlJaSoYwSFDhqEJIUiFIQMgjSENDSCLIQ0hjoEAKAhIaAhKwWjghiE" + 
			   "GBiCGBgEhjoiMZAxkDFxMZCQkACCNIQshSKEJIImNgQ2hiYArCddHZ4trJ+FFIIghCIsHh6CLCwe" + 
			   "BIcqQEBAOjaCNCwEJoYiAOP39/f18awnnp2FGIIehCIqIiKCLCwiBIYEgio2BDaHNjQwhiwEAABo" + 
			   "amxFojGw8e3roh2clYYEhSKCIociJiqELCKGFFGQMREAgCIoIiYiJCImIigiKiIoIiYiKCImIiQi" + 
			   "JiIoIioiKCImICYgJCAmICggJiAoICYgJCAmICQgJiAoICYgKCAmICQoMCgyKDAoLigwKC4oLCgu" + 
			   "KDAoMigwKC4oMCguKCwoLgAEcG5sbnBycG5wbmxucHJwbm5sbnBucG5sbmxucG5wbmx2eHZ0dnRy" + 
			   "dHZ4dnR2dHJ0hBqDGCCEHoMcKCYcGhyCLAQEIgQEhByHJiomhCQoJIAiAJwFlAUNnx6cmJ2CIgQE" + 
			   "HAQEhBSGHoAWgBSBHDAEMDAEHjIEMjIEIDQENDQENgSENgBGpGSkSKZmpkqoaKhqRCuBKkIEQkIE" + 
			   "LGQEZGQELkYERkYEIgSEIocEBgwUHCKGLCKHBGAOFBokhiwkhwQIEBgeKIYwMIBkAM3V3ePt9bu1" + 
			   "z9Xb5e3zvbPR2d/p8fe/////NACGBIcUHCKGNIQsBAQEhxQaJIYyhCwEhgSHGB4ohjaHMDAwgCyC" + 
			   "FCxiJhAogASCFCxiJhAogASCCB5eGGAagASCCB5eGGAahgSDGhgWhBQaGA4MFoMUIB4cKCaHJBoS" + 
			   "EGIOgAQEAIIYHCAiJiiBKioqBCoEgyqCIoY0MjSBBCImKiwwhjSDMoI2hDSFBIEihjAuMIEEIiYq" + 
			   "LC6GMIMigjaENIUEgSKGOjo6gjqBQIIEgTqGNjY2gjaBOoIEgTaGNIImKjaBNDSFNIEqhiwAhJCw" + 
			   "hFBQsACYlpSSlJZYWFhEXESfo6GjhaPgpiPEn52fhZ/SpiPEtbGvhbGvrYWVnqKqamprXp2EBASC" + 
			   "IoYighQiLBIiKhQiLBwiLBQiLBIiKhQiLBwiLBgiKhYgKBgiKhIiKhgiKhIiKhQiLAwiLBQiNBIi" + 
			   "MBAiLhYiNBgmNhYmNhQmNhIiNlwiNAwiIoEeHoUegRKGFIEsIhwsIhyFLASBLiQeLiQehS4EgTIo" + 
			   "IjIoIoUyhzY2NoQ6AFxUTFxUTFwcHFxcXFxeVk5eVk5eHh5eXl5eYlpQYlpQYiIiYufn5yuGFIEU" + 
			   "gBQUgRQUFBSGFoEWgBYWgRYWFhaBKCIaKCIaKIAoKIEohywsLIQwgwSEDINiEIQSgxwiHiImGB4E" + 
			   "HADj4eMd3uAj7HV08PT26jEtgxIUBBgaHBQmIh4cGB4iDBT///8AiAAvAAACpgKAAlwCOgIaAd8B" + 
			   "xAGrAZMBfAFnAVMBQAEuAR0BDQD+AO8A4gDVAMkAvgCzAKkAoACXAI4AhgB3AH4AcQBUAGQAXwBZ" + 
			   "AFAARwBDADsANQAqACMEdQNXAvkCzwH8AGoFChQoUB48AgQIECBAGDAMAwYMGDASJAg2AwkGEhsk" + 
			   "DCQCBgQMEhgIEgEDAgYJDASYmZqbkJSUlZWWl5iQkZKSk5OTlJSUlJSUlZWVlZWVlpaWlpaWlpaW" + 
			   "lpaWlpaWlpaVlZSTFRYWFxcYGRkaGhwdHR4eHx8fHx4dHB4fHx4dHBoYFhQVFhYXFxgZGRoaHB0d" + 
			   "Hh4fgoAAgPD/Aw8fHxwkJmYAAAAAHz8/f+DAgPyAwAAgACBgAPD8/v5gcBgHDx8/f39/HwcAHj9/" + 
			   "/HwAAODw+Pj8/PjAwmcvN39///8HBw8Pf3788Pj48HD9/rT4+Pn7/zc2XAAAAQMfHz////xwcDgI" + 
			   "JOPw+HBwOP///x8AAAAAHx8fHwAAAAAAAAEHDw8OEgAAAAAAAA8fAADw4MD+QGAAAAAQMAD4/hMz" + 
			   "MBgEDx8fHz8/HwcIFxcAEH4+AADA4P///v784ECgPz8/Hx8fHx83JyMDAQAAAPDw8Pj4+Pj4zP//" + 
			   "//9wAAj////+8MCAAPDw8PDwwIAA/Pz4eHh4fn4QYIAAeHh+fgADDx8fHCQmAAAAAAAfPz8A4MCA" + 
			   "/IDAAAAAIGAA8Pz+ZmAwGA8fPz9/fz8fABYvLyD8fAAA4ODw/vz8+MBgIDA/Pz8/Pz8/Hy8vLw8H" + 
			   "AwAA8JAACAwc/PgQ8PDw8ODA4A8PBwcHDw8DAQMBBAcPDwP48ODwsIDg4Pjw4HCwgODgAz9/GQkJ" + 
			   "KFwAMHB////38/jg4PwmMIAQABgQAPj4/v8+Hj84MDAAOucPDx8fHw8HeB6A/n5+f3///vzGju7/" + 
			   "/zw/Hw8HPyEgAwAADgc/Pz/////+/v78cP9/Pw7AwODgD5/P/38/Hg4AgMj+fz8eDiDAgIAAAAAA" + 
			   "4AAAAAAAAAAAAAMPHx8cJAAAAAAAAB8/AATm4P//j4MOHx8fHwP//yYmYHgYD3//Pz9/fx8Afv8B" + 
			   "If56Bv78/P///v7+3lxs/8+HBwcPHx////78+LBgAPj48Lj4+fv/KDAYQAABAw8f//////7AgBDs" + 
			   "4+Dg4MCA////PwAAAAAPDw8PAAAAABMzMBgEDx8fHz8/HwcJExcAEH4w4PDw4P///v/+/PjgHx8P" + 
			   "Dw8fHx8XFwMAAAAAAPDw+Pi4+Pj40JAYCEAAAAA/////9saEADDw8PH2xoQA8OCAAAAAAAAAAAAA" + 
			   "AAAAAB8fPz8fDw8fHx8/Pnx48ODw8Pj4uPj48LCQGAhAAAAA4PDw8PDw+PDA4Pz+/38DAB8fHz8+" + 
			   "PDgYAAAQOD48OBgAAwcHCgsMAAAAAAcPDw8DAOD8ICAQPAAAAADw/P78+AcHBx8fPiEBBw8bGBAw" + 
			   "IQHg4ODw8ODA4Kj8+AAAAMDgBw8OFBYYAD8AAA8fHx8HPMD4QEAgeADAAADg+Pz48MA/Dg8fP3xw" + 
			   "OPztwAAAYHA48Pjk/Px8AAB+HgQMDAwAAAcPDhQWGAAPAAAPHx8fBw0fHx8cDAcHBx4cHg8HAAcH" + 
			   "4GDwcODg8IBgkACAAODwgAcfPxITCB8xABA/f38/Aw/A8EAAMBjA+AAA4Pj8+LA4MTkfHw9ffjwf" + 
			   "BwAOD1N8PPj48ODgwAAA+PjwAACAAAAA4PwnJxE+BAcHA/f///78P38/Dx8/f08+f//iUDhwQPj5" + 
			   "+bf//+AA6HEBSwMDAAAHBw8/Pz8mBAUDATAwMCYE8PDw4MAAAAD+/OAAAAAAAAcHDx8/DxwYBQMB" + 
			   "EDAMHBjg4ODgwIAAAMDg8HgYCAAABw8fDz8PHBgHDz58MAwcGODg4EDAgAAAYGBggAAAAAB////7" + 
			   "Dw8PH3Pz8PTw8HBgP358fDw8/PwAAAAAPDz8/GBwGAgPHz9/f38fBwsbO3v8fAAg8Pj8/vz8+ODQ" + 
			   "2NzeCw8fHjw8PHzE4OBAADw8fB8/DQcPDhw8HTw6ODAAHDwAAAAAAAAAACJVVVVVVXciAAcf/wcf" + 
			   "DwYAAAAAAAAAAD////////t2AADPB38AAAAg+P/D/f7wQAAAPPz+4AAAQOBAQEFBT0dA4EA/Pj4w" + 
			   "OAAAAAAAAODAAAAA+Pj4GDhDRkRAQEBAQDw5Oz8AAAAAgMBAAAAAAAB4OLj4AAAAADEwOHx////7" + 
			   "Pz8Pd3f39/cQfj4AHv7////+/v76+vPn///jw4dIPPzw+Px8eDg8/AD/w4OD/////wDDgYHD/wAf" + 
			   "Hw8HAQAAAAAAAAAAAAAA8Pv///4+DAQACx8fHj4MBB8fDw8HAAAAAAAAAAAAAAD7/////wAAAAMP" + 
			   "Dw8PAAAAABg8fm7f398AGDx+dvv7+wAYGDw8PDwcABAQICAgICAACAgICAgIAAAICAgICAgIAAgI" + 
			   "BAQEBAQAEBA4ODg4ODx+d/ufX44gABg8Dg4EAABcLo8/e3d+PAAABAYePBgAE08/vz96+PgAAAEK" + 
			   "Fw8vHwAIBQ8vHRw8AAAAAAUHDwcAAAAAAgsHDwAAAAAAAAEDAAAAAAAIBAQAYPD4fD5+fwICAgVx" + 
			   "f39/P19/Pg4KUSAAAAAAAAAABAAAAAAAAA4fAgIAARM/f38/f3/+7MpRIABAYHBzJw8fAEBjd3w4" + 
			   "+OQAAAAAAwcPHwAAAwcMGPjkf38/Px8fDwcDRCgQCAQDBAMHDx8/d3f1AwcPHyd7ePvA4PD4/O7u" + 
			   "r8Dg8Pjk3h7f8f94AAAYHA7//38PDwcDAI//HgAMPn58///+8PDAgAAAAAAAAAAAAAAAGCQkGAAA" + 
			   "AAJBQWEzBjw8fv////9+PAMHDx8/f3//AwcPHz9jQcHA4PD4/P7+/8CAAACM/v7z////eAAAAADB" + 
			   "4/9HDw8PB////x4AICBA8fn/4vDw8OAWHz9/PR0/HxYfAAAFDT8fgIDA4PDw8PiAgAAAAKCg4Dz6" + 
			   "sXLy299fAAROjAx///8AAAABAQEGHgAAAAAAAAEBAAAAAAAAAAD/fz8fDwcDAQB81pK67v44/4Mp" + 
			   "bUURAccAFT9iX/+ffQgIAh8iAgIAAAAAAAAAAAAICAgICAgICC8eLy8vFQ0OEB4QUBAIAAAAAAAA" + 
			   "AAAAAAAAAP4AAAAAHD5////+fDgcKnfu3ap0KAD///////////7+AO/v7wD///////////7+/gDv" + 
			   "7+8Af/////////8Af19/f39/f2hO4ODg8Pj8uJ6AwODw+Hw/XDk7u/n8/gAjV09XJ8MhwPDw8PDg" + 
			   "wAAAMHBw8ODAAP78YQ///vDgEw8e8Pz48OBuQODg4ODgwL6QgMDAgAAAAQEDAwd/fz8BAQMDB399" + 
			   "PQYHPzwZe38/BgQwIwZkYAA/f38fPz8HBgBgYAAgMAQGAwcPDw8PBwMAAQEAAAAAAPj4+KDh////" + 
			   "/v//QAEDAwMPDw8fHx8PBwEBAAAAAAAA4Pj4+P/+8MDg/v9/AwIAAAEPDx85Mzd/AQ0IADYsCGB/" + 
			   "Pz8/Hw8PAWAAIDAACA0BAAADA0dnd3cBAQNDZ3d7eAAAAACImPjwAACAhMzcvDx+f/8fBzAcDDMH" + 
			   "B+M4PxwMfjj27d84cGCYx8iSMPhwYAAAAAMDR2d3AAEBA0Nnd3sAAAAAAIiY+AAAAICEzNy8d35/" + 
			   "/x8HcPB4MwcH4zh/8PB+OPbt3zg8PJjHyJIw+DwDBwoaHB4LCAAQf39/Hw8PHD8/PT8fAAADMzk6" + 
			   "OBgAAAAABExOTkZvEDg8dHZ2fn0AHz8/T19/fwAAEQo0KlEgf2ejsNje3Mh/Z2NwOD58uH9/fx9H" + 
			   "cHA5UQoE6nl/cDno6ODAEHDgwFg4EDDw8ODAAAAAIGZmZmIACBw8enp6fgAAHz9/T19/AAAAEQo0" + 
			   "KlF3fz+3s9va2H99PzczOzp4f39/fx8HcPAgUQoE6jl/8Mzo6ODAGHw+vFg4EDD4/D4DDx8/Oz9/" + 
			   "fwAAAAYODAAAgPD4/P7+//4AAAAAAAAPGH9/f3//DwMAAAAAAPg+Oxj++///9uDAABAUEBA4ePgw" + 
			   "AAMPHz87P38AAAAABg4MAADA8Pj8/v7/AAAAAAAAAA9/f39/f/8PAwAAAAAA+H7z/v77///24MAY" + 
			   "EBQQEDh83gABAQEBAAAIAA0eHh4fDwd48PjkwMrKwHjwABo/NTU/Dx+f//9/dCAAAIDg4HBzIeT/" + 
			   "/vycHgAAGgcMGHj+/PAAAQMDBwMBAAABAgA4fH4/AF9/fz8/FAA/QGBgIDATAcDg8DA4PDz8wOAw" + 
			   "0NDQ0AAHDx8iICUlHwcPAh0fGhoC/v5+OgIBQUE4fPz8/P6+vh8/flxAgIKCHD4/Pz9/fX2CgKBE" + 
			   "Q0AhHn1/Xzs8Px4AHD8+PECAgoIcPj8fP399fQAAgICSncfvAAAAYGJlPx8AIzM/P39/f3A8PBgA" + 
			   "AAIH/vigAAAAgIDPeloQAADAgH5/fT8ej48ZhYSGxudzc+HgDnPz+fn4cIBOd/P7+fp4Dmbi9v//" + 
			   "H5gROX05AADg5wAAAAQPDx8HAAAHBxYQADjz5+7szc/P388fFxAzMDAgJz8/eDwfH3M4MEDHB2bg" + 
			   "bJ8+fPz4+MBAYMCABJ7/8Ph/fngBBx88fCQBB/7/fz9//Pig/vzwgADPegr+/AAAAH5/fz8fj48Y" + 
			   "hYaDw+FwcOCfPnz4+DwY+GDAgACY/P7/f394AQcT8QMkAAf+/3//AwAAHB0bw+PhAw8jYmQ8HB7g" + 
			   "zR1P7v8/Px89bU/u8yADPz8AAHC4/PwHBx8/D0cDAAcPHz8+fHh4AAADBw8PHx8/XDk7v//+/gAj" + 
			   "V09XL98hwMCAgICAAAAAAAAAgIAAAP78YQ9/Px8eIw8e8Bw/Hx7weOTIzL6+PgCAGDA0/v7+AAEA" + 
			   "BwcHBx8AAAEEBgYHBwAADz8/DwAADz9/+Ph/Pw94fH5/Pz8bCR8fHwsBAQAADAAAAAd/fAADHz8/" + 
			   "eAAD/wHhcXk9PR8DAAAAAAAAAAA/Px8bNjB/PyMnHwcPH38/+Pj4uBjY2LjggIBA4ODgwAECBAQI" + 
			   "CBAQAwcPHz9//x8ADxMNDRMMIB8QDBISLD8/ACQAJAAEAAA3NjY2FhYSAg9BAIgARAAAEH7///Z2" + 
			   "Oho4fP7+OwMDAwAAOAQAAAAAAzN7f//7AwMAAAA4QAAAANzA4ODg4ODA/KCAgAAAAAA/Xz8/u/j+" + 
			   "/gcnV09XJ8EhHw8PHx8eODAdDw8fHx44MAAgYGBw8Pj4AAA4EEwYhiT4/Px+fj4fBwBCCkAQAggC" + 
			   "AMBwuPTy9XsAAIBACAwKhADfEP/f///5AADPICAgJi4fHz78+PDAAODgwAAAAAAA+Pz+///f3wAv" + 
			   "IyEgIAAAAMHxeX09Px8DwbFZbTU7HwMCBg4OHh4+PgACAAgCACgAPj4+Ph4eDgIEEAIQBAAKAMHx" + 
			   "eX09Px8DwbFZbTU7HwN8AAD/w38fAwAPH//8Yx8D//98AAB8//8AAP7Gxv4AAP//AAQMGDAAAAAG" + 
			   "BgwYcGD//wAEBAQICAAABgYEBAgICBAQAAAQEAgIEDAwMDAQCH8/Pz4fDwMAAAABAwEAAAADD/9/" + 
			   "f39/fwMO+AAAAAAAAAAAAAAAAAAiZSUlJSV3cgAAAAAAAAAAYpUVJUWF9/IAAAAAAAAAAKKlpaX1" + 
			   "9SciAAAAAAAAAADyhYXlFRX34gAAAAAAAAAAYpVVZbWVl2IAAAAAAAAAACBQUFBQUHAgAAAAAAAA" + 
			   "AAAAAAAAAAAAAAAAAAAAAAAAZuZmZmZn8wAAAAAAAAAAAF5ZWVle2JgAAAAAAAB8OAAAAAAAAAQI" + 
			   "ADhMxsbGZDgAAAAAAAAAAAAYOBgYGBh+AAAAAAAAAAAAfMYOPHjg/gAAAAAAAAAAAH4MGDwGxnwA" + 
			   "AAAAAAAAAAAcPGzM/gwMAAAAAAAAAAAA/MD8BgbGfAAAAAAAAAAAADxgwPzGxnwAAAAAAAAAAAD+" + 
			   "xgwYMDAwAAAAAAAAAAAAfMbGfMbGfAAAAAAAAAAAAHzGxn4GDHgAAAAAAAAAAAA4bMbG/sbGAAAA" + 
			   "AAAAAAAA/MbG/MbG/AAAAAAAAAAAADxmwMDAZjwAAAAAAAAAAAD4zMbGxsz4AAAAAAAAAAAA/sDA" + 
			   "/MDA/gAAAAAAAAAAAP7AwPzAwMAAAAAAAAAAAAA+YMDOxmY+AAAAAAAAAAAAxsbG/sbGxgAAAAAA" + 
			   "AAAAAH4YGBgYGH4AAAAAAAAAAAAeBgYGxsZ8AAAAAAAAAAAAxszY8PjczgAAAAAAAAAAAGBgYGBg" + 
			   "YH4AAAAAAAAAAADG7v7+1sbGAAAAAAAAAAAAxub2/t7OxgAAAAAAAAAAAHzGxsbGxnwAAAAAAAAA" + 
			   "AAD8xsbG/MDAAAAAAAAAAAAAfMbGxt7MegAAAAAAAAAAAPzGxs743M4AAAAAAAAAAAB4zMB8BsZ8" + 
			   "AAAAAAAAAAAAfhgYGBgYGAAAAAAAAAAAAMbGxsbGxnwAAAAAAAAAAADGxsbufDgQAAAAAAAAAAAA" + 
			   "xsbW/v7uxgAAAAAAAAAAAMbufDh87sYAAAAAAAAAAABmZmY8GBgYAAAAAAAAAAAA/g4cOHDg/gAA" + 
			   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////////wAAAAAAAAAAAAAAAAAAAAD/////////////" + 
			   "//////////////////8AAAB+fgAAAAAAAAAAAAAAAABEKBAoRAAAAAAAAAAAAP//////////f39/" + 
			   "f39/f38YPDw8GBgAGAAAAAAAAAAA/39/f3//48H/gICAgAAcPoCAgMHj////f39/PhwAAP84fHx8" + 
			   "fHw4AAgEBAQEBAgAAwYMDAgIBAMDBQsLDw8HAwECBAgQIECAAQMHDx8/f/8AAAAAAAc4wAAAAAAA" + 
			   "Bz//AAAAAADgHAMAAAAAAOD8/4BAIBAIBAIBgMDg8Pj8/v8EDg4ObmRgYP//////////Bw8fH3//" + 
			   "/38HCBAAYICAQAMHHz8/P3n3AwQYICAgRojA4PD0/r/f/8AgEBQKQSEBkLj4+v////6QqEgKBQEB" + 
			   "AjsdDg8HAAAAJBIJCAcAAAD/vxzA8/9+HABA4z8MgWIcv389g8f//zxAgMJ8OADDPPz+//7++GAA" + 
			   "BAIBAAaYYADAIBAQEBAgwMDg8PDw8ODAAAAAAD9/4MAAAAAAAAAcPoiciICAgICAf39/PhwAAAD+" + 
			   "/v7+/v7+/v//////////CBQkxANAoSYACBg4/L9e2f////9/f39/gYGBgYGBgYH//////////wEB" + 
			   "AQEBAQEBf4CAmJyMgIAAf39nZ39/f/8BAf8QEBD/AP////////+AgICAgICAgH9/f39/f39/AQEB" + 
			   "/xAQEP////////////8AAAAAAAAAAP/////////+AQEZHQ0BAQD//+fn////AQEBAQEBAQH/////" + 
			   "/////z9/f///////P2BAwICAgID///////9+PICAgICAgUI8////////////AAAAAAAAAP//////" + 
			   "//58AAAAAAABgnz////////+fAAAAAAAAYP/+Pz+/v/////4BAICAQEBAf///////348AQEBAQGB" + 
			   "QjwACAgIEBAQAP//////////AH9/eHNzc39/gKCHj46OhgD//z+fn58f/gEFweFxcfF+fn9+fn9/" + 
			   "/4GBgIGBoID/f3//f3/////xwcGBwcUB/3+AoICAgICAf//////////+AQUBAQEBAf7/////////" + 
			   "gICAgICggH//////////fwEBAQEBBQH+//////////4AAAAA/P4HAwAAAAAAADh8ETkRAQEBAQH+" + 
			   "/v58OAAAAO8oKCgoKO8AIOfn5+fn7wD+goKCgoL+AAJ+fn5+fv4AgICAmJyMgH9/f39nZ39/f///" + 
			   "g/Pz8/Pz/4D8jIyMjIz///D29vb29v8ADwkJCQkJ//8AAAAAAAD/AP//////////AVcvVy9X/wH/" + 
			   "qdGp0anz8/Pz8/P/P4yMjIyMjP8/9vb29vb2//8JCQkJCQn//wAAAAAAAP////////////8vVy9X" + 
			   "L1f//NGp0anRqf/8PDw8PDw8PDwjIyMjIyMjI/v7+/v7+/v7BAQEBAQEBAS8XLxcvFy8XESkRKRE" + 
			   "pESkHyBAQICAgIEfP39//////v+AgMD///7+/39/PwAAAQH/f3///wcDA/+AgAAA+Pz8/wAAAACB" + 
			   "w////////348APj8/v7jwYGB+AQCAh0/f3+D//////9/H/yAgICAgGAf/Pz8/P7+//8DAwMDAQEA" + 
			   "/wEBAQEDAwf//v7+/vz8+P///////////wAAAAAAAAD/gcHj//////5/Px0BAQED/v//////+7XO" + 
			   "gICAgICEyrH//////9+tcwEBAQEBIVONd3d3d3d3d3cAAAAAd////wAAAAAAAAD///////////93" + 
			   "d3d3AAAAAP///3d3d3d3AQEBGR0NAf7////n5////iB4f/7+/v7+ACEhQUFBQUEEmvr9/f39/QCA" + 
			   "gICAgICAfjghAAEAAQAhIQEBAQEBAfqKhICAgICAgICAgICAgIACBAAQAECAAAEBBggYICDACws7" + 
			   "C/sLCwoEBMT09AQEBZAQHxAfEBCQcPDw///w8HA/eOfPWFhQkMCHGLDn5+/vsPziwcGDj35vQ10/" + 
			   "P39///4DD5FwYCAxA//xbs/f//8/Px05e/OG/v37+/f3D3////////+AgP//gICAgP//gP7/////" + 
			   "AwP//gMDAwP//wMA//////8AAAD/AAAAAP//PPz8/Pz8BAQj8wsLCwf///////+A////gICAgP+A" + 
			   "gID/////A////wMDAwP/AwMD//////8A//8AAAAAAP8AAPz8/v7+Av7+BwcDAwP/AwP/gICAgICA" + 
			   "gID//////////wMDAwMDAwMD/////////wICAgICAgQE//////////+AgKrVqv//////1arVgID/" + 
			   "AwOrV6v///7//1erVwMD/gBVqlX///8A/6pVqgAA/wAEVKxc/Pz8PP+vV6sLC/MjPz8/PwAAAP//" + 
			   "/////////358fHgAAAD///////////8fDw8HAAAA/////////////vz8+AAAAP///////////wAA" + 
			   "AAD//wAAAAAAAAAAAAAYGBgYGBgYGAAAAAAAAAAABx8//39//////////////+H5/f/+/v//////" + 
			   "///////wEBAQEBAQ/wDg4ODg4ODgHxAQEBAQEP8ADw8PDw8PD5KSkv7+AAAASEhsAAAA/gAKCjoK" + 
			   "+wsLCwUFxfX0BAQEkJCfkJ+QkJBwcHB/f3BwcAEBAQEBAQEBAAAAAAAAAACAgICAgICAgAAAAAAA" + 
			   "AAAACIiR0VNTcz////////6+zgAABw8MGxsbAAAAAAMEBAQAAODw8Pj4+AAAYDAwmJiYGxsbGxsP" + 
			   "DwcEBAQEBAMAAPj4+Pj48PDgmJiYmJgwMGDxEREfEBAQ/w/v7+/v7+/gHxAQ8BAQEP/g7+/v7+/v" + 
			   "D3+/3+/w8PDwgEAgEA8PDw/w8PDw/////w8PDw8fP3///////w8PDw8BAwcP/////w8PDw/3+/3+" + 
			   "//////////8AAAAAAAAYGAAAAAAAAAAAHz9/f3////8fIEBAQICCgv///39/fz8egoCgRENAIR74" + 
			   "/P7+/v////gEAgICAUFB/////v7+/HhBAQUiwgKEeH+AgICAgICAgH9/f39/f3/eYWFhcV5/YWHf" + 
			   "39/f/8HfgIDA8L+PgX5/f/8/T3F//2FhwcGBgYP+39+/v39/f38AAAMPHz9/fwAAAwwQIEBAAADA" + 
			   "8Pj8/v4AAMAwCAQCAv//////////gICAgICAgID//////////wEBAQEBAQEBf39/Pz8fDwdAQEAg" + 
			   "MBwPB/7+/vz8+PDwAgICBAw48PAPDw8PDw8HDwgICAgIDAUK8PDw8PDw4PAQUFBQUDCgUIHBo6Od" + 
			   "gYGBAEEiIhwAAADj98HBwcH34+MUPj4+PhTjAAAHDwwbGxv///jw8ODg4AAA4PDw+Pj4//9/Pz+f" + 
			   "n58bGxsbGw8PB+Dg4ODg8/D4+Pj4+Pjw8OCfn5+fnz8/f+D/////////AHAfEHB/f38H////////" + 
			   "/wAD+AAD+/v7///////+/+98e3Z1dXcXZ//f76+vb+/nO/t7+/vz+PMfHz8/cGPn5Q8PHx8/PHh6" + 
			   "8PD4+AzE5Kb4+Pz8/j4eX+np6e/i4/D/dnZ2cH18f3+Wlpb2RsYO/m9vbw+/P///AAAAAAAAfjw8" + 
			   "fn7///9CADxCmaGhmUI8AAAAAAAAAAAPHx8/P39/f/Dg4MDAgICA8Pj4/Pz+/v4PBwcDAwEBAX9/" + 
			   "Pz8/Px8fgIDAwOD4/v/+/////Pz+/v9/HwcDAwGBf39/Pz8/Px+AgIDAwODg8P7+///////+AQEB" + 
			   "AwMHBw8fDw8HAAAAAP///////////vz8+AAAAAD//////////35+fn5/f39/gYGBgYGBgYH/////" + 
			   "/////gEBAQMDBwcP/v7+/v////8BAQEBAQEBAX9/f39/f39/gYGBgYGBgYH//////P7+fv8DAwMD" + 
			   "AwP//////wAAAAD//////////39/f39/f39/gICAgICAgID//////////gEBAQMHAwEBfn5/f39/" + 
			   "f3+BgYGBgYGBgT8/Pz8AAAAA//////////9+fHx4AAAAAP///////////v7//39/f3+BgYGBgYGB" + 
			   "gX9/Pz8/Px8fgIDAwOD4/v8/v////Pz+/v9/HwcDAwGBf39+fn9/f3+BgYGBgYGBgX5+fn5/f39/" + 
			   "gYGBgYGBgYGBw8Pn5////348PBgYAAAAD0NbUzEZDwfy/v7//+/3+MHDxoT8/A4Cv769e3sH8/0Q" + 
			   "ICK65uHAwP///2dZnr+/IKZUJiDGVCYg5lQmIQZUJiCFAUQghlRIIJoBSSClyUYguslKIKYK0NHY" + 
			   "2N7R0Nre0SDGCtLT29vb2dvc298g5grU1dTZ2+LU2tvgIQYK1tfW1+Em1t3h4SEmFNDo0dDR3tHY" + 
			   "0NEm3tHe0dDR0NEmIUYU20JC20LbQtvbQibbQttC20LbQiYhZkbbIWwO39vb2ybb39vf29vk5SYh" + 
			   "hhTb29veQ9vg29vbJtvj2+Db2+bjJiGmFNvb29tC29vb1Nkm29nb29TZ1NnnIcUWX5WVlZWVlZWV" + 
			   "l5h4lZaVlZeYl5iVeiHtDs8BCQgFJBcSFx0OFw0YIksNASQZFQoiDhskEAoWDiKLDQIkGRUKIg4b" + 
			   "JBAKFg4i7AQdGBkoIvYBACPJVlUj4gSZqqqqI+oEmaqqqgD///////////////////8="];
function Main()
{
	var document = Controls.Document;
	var jsnes = Controls.NES;
	
	var AUDIO_BUFFERING = 512;
	var SAMPLE_COUNT = 4*1024;
	var SAMPLE_MASK = SAMPLE_COUNT - 1;
	var audio_samples_L = new Float32Array(SAMPLE_COUNT);
	var audio_samples_R = new Float32Array(SAMPLE_COUNT);
	var audio_write_cursor = 0, audio_read_cursor = 0;
	var audio_ctx = null;
	
	var canvas = null;
	var context = null;
	var imageData = null;
	var buf = null;
	var buf8 = null;
	var buf32 = null;
	
	function audio_remain(){
		return (audio_write_cursor - audio_read_cursor) & SAMPLE_MASK;
	}
	
	function audio_callback(event){
		var dst = event.outputBuffer;
		var len = dst.length;
		
		// Attempt to avoid buffer underruns.
		if(audio_remain() < AUDIO_BUFFERING) nes.frame();
		
		var dst_l = dst.getChannelData(0);
		var dst_r = dst.getChannelData(1);
		for(var i = 0; i < len; i++){
			var src_idx = (audio_read_cursor + i) & SAMPLE_MASK;
			dst_l[i] = audio_samples_L[src_idx];
			dst_r[i] = audio_samples_R[src_idx];
		}
		
		audio_read_cursor = (audio_read_cursor + len) & SAMPLE_MASK;
	}
	
	function initCanvas() {
		canvas = document.getElementById("myCanvas");
		context = canvas.getContext("2d");
		imageData = context.getImageData(0, 0, 256, 240);
		
		context.fillStyle = "black";
		// set alpha to opaque
		context.fillRect(0, 0, 256, 240);
		
		// buffer to write on next animation frame
		buf = new ArrayBuffer(imageData.data.length);
		// Get the canvas buffer in 8bit and 32bit
		buf8 = new Uint8ClampedArray(buf);
		buf32 = new Uint32Array(buf);
		
		// Set alpha
		for (var i = 0; i < buf32.length; ++i) {
			buf32[i] = 0xff000000;
		}
		
		// Setup audio.
		audio_ctx = new Controls.AudioContext();
		var script_processor = audio_ctx.createScriptProcessor(AUDIO_BUFFERING, 0, 2);
		script_processor.onaudioprocess = audio_callback;
		script_processor.connect(audio_ctx.destination);
	}
	
	function setBuffer(buffer)
	{
		var i = 0;
		for (var y = 0; y < 240; ++y) {
			for (var x = 0; x < 256; ++x) {
				i = y * 256 + x;
				// Convert pixel from NES BGR to canvas ABGR
				buf32[i] = 0xff000000 | buffer[i]; // Full alpha
			}
		}
	}
	
	function writeBuffer()
	{
		imageData.data.set(buf8);
		context.putImageData(imageData, 0, 0);
	}
	
	function play()
	{
		nes.frame();
		setTimeout(() => {
			play();
		}, 13);
	}
				
	// Initialize and set up outputs
	var nes = new jsnes.NES({
		onFrame: function(frameBuffer) {
			// ... write frameBuffer to screen
			setBuffer(frameBuffer);
			writeBuffer();
		},
		onAudioSample: function(l, r) {
			audio_samples_L[audio_write_cursor] = l;
			audio_samples_R[audio_write_cursor] = r;
			audio_write_cursor = (audio_write_cursor + 1) & SAMPLE_MASK;
		}
	});
		
	initCanvas();
		
	// Load ROM data as a string or byte array
	nes.loadROM(atob(romData[Math.floor(Math.random() * romData.length)]));
		
	// Run frames at 60 fps, or as fast as you can.
	// You are responsible for reliable timing as best you can on your platform.
	play();
		
	document.addEventListener('keydown', (event) => {
		const keyName = event.key;
		switch(event.key)
		{
			case 'Enter':
				nes.buttonDown(1, jsnes.Controller.BUTTON_START);
				break;
			case ' ':
				nes.buttonDown(1, jsnes.Controller.BUTTON_SELECT);
				break;
			case 'x':
				nes.buttonDown(1, jsnes.Controller.BUTTON_A);
				break;
			case 'w':
				nes.buttonDown(1, jsnes.Controller.BUTTON_B);
				break;
			case 'ArrowRight':
				nes.buttonDown(1, jsnes.Controller.BUTTON_RIGHT);
				break;
			case 'ArrowLeft':
				nes.buttonDown(1, jsnes.Controller.BUTTON_LEFT);
				break;
			case 'ArrowDown':
				nes.buttonDown(1, jsnes.Controller.BUTTON_DOWN);
				break;
			case 'ArrowUp':
				nes.buttonDown(1, jsnes.Controller.BUTTON_UP);
				break;
		}
	});
		
	document.addEventListener('keyup', (event) => {
		const keyName = event.key;
		switch(event.key)
		{
			case 'Enter':
				nes.buttonUp(1, jsnes.Controller.BUTTON_START);
				break;
			case ' ':
				nes.buttonUp(1, jsnes.Controller.BUTTON_SELECT);
				break;
			case 'x':
				nes.buttonUp(1, jsnes.Controller.BUTTON_A);
				break;
			case 'w':
				nes.buttonUp(1, jsnes.Controller.BUTTON_B);
				break;
			case 'ArrowRight':
				nes.buttonUp(1, jsnes.Controller.BUTTON_RIGHT);
				break;
			case 'ArrowLeft':
				nes.buttonUp(1, jsnes.Controller.BUTTON_LEFT);
				break;
			case 'ArrowDown':
				nes.buttonUp(1, jsnes.Controller.BUTTON_DOWN);
				break;
			case 'ArrowUp':
				nes.buttonUp(1, jsnes.Controller.BUTTON_UP);
				break;
		}
	});
}

setTimeout(Main, 0);